### ISSUE TITLE
ZT Client on DS414 not working

### ISSUE THREAD

**Issue by hteibler** [zerotier/ZeroTierNAS#10]
Installation on DSM 414 is finishing
but you can't join a network
click on join has no response
and the zt prozess is consuming 50% CPU
stopping not working
deinstall doesn't stop prozess
need to reboot the DSM

**Comment by joseph-henry** [comment]
Your device uses the Armada XP MV78230 Processor. Try this: https://download.zerotier.com/dist/zerotier-1.2.4-syn-armadaxp-6.1.spk

Since I don't have one of these devices in-house it would be fantastic if you could let me know if this fixes your problems (or creates others).

Thanks

**Comment by hteibler** [comment]
Hello joseph-henry
looks good
install OK
Join OK
CPU Load OK
thanks, herbert
