### ISSUE TITLE
Synology DS220j - DSM 6.2.4-25556 - Shows Offline

### ISSUE THREAD

**Issue by Brooklyn727** [zerotier/ZeroTierNAS#105]
I was able to connect to my NAS with Putty and use the command line to verify that Zerotier was running and I was able to join the network with it. However, when I click on the Zerotier package in the package center, it still tells me that it is OFFLINE. 

### I have tried the following:

- [X ] Disabling QuickConnect
- [X] Disabling OpenVPN
- [X ] Restarting NAS
- [X ] Reinstall ZT

**Comment by Phil-von-Moscado** [comment]
Same problem here.

Fresh DS220+

No Quickconnect, no VPN, nothing else.

Tried actual version, the version before and 1.2.12

Nothing is working GUI only reacts if i dont insert a Net ID nothing else.

Shell:
`ash-4.3# cd /volume1/@appstore/zerotier
ash-4.3# ./bin/zerotier-one 
./bin/zerotier-one: fatal error: cannot bind to local control interface port
`

**Comment by Phil-von-Moscado** [comment]
And there is no zerotier-cli

**Comment by bionemesis** [comment]
You can use the cli by running /volume1/@appstore/zerotier/bin/zerotier-one -q. So for example:

/volume1/@appstore/zerotier/bin/zerotier-one -q join d5ke39289391xxxx

**Comment by joseph-henry** [comment]
The GUI has known issues and has been deprecated for some years now. We'd only recommend using the CLI at this point.

Here are the latest [1.8.6 packages for DSM 6.2.4](http://download.zerotier.com/RELEASES/1.8.6/dist/synology/). We'll continue to periodically make releases for DSM 6 until Synology officially EOLs it in 2023. But I would recommend using our [docker solution for DSM 7](https://docs.zerotier.com/devices/synology). I'm going to close this ticket but if you have any issues please don't hesitate to open another ticket detailing what you tried. Thanks.
