### ISSUE TITLE
[Synology 1817+ (Avoton)] "Join" button has no effect / zerotier-cli command not found

### ISSUE THREAD

**Issue by cinghialino** [zerotier/ZeroTierNAS#11]
Hello, 

I'm using Zerotier on my **Synology 1817+** with **DSM 6.1.4-15217 Update 2**
I have installed the package 

- **zerotier-1.2.4-syn-avoton-6.1.spk** and

-  **zerotier-1.2.4-syn-x64-6.1.spk**

 but unfortunately this does not work. No effect when pressing the JOIN button on the interface, and also, accessing Zerotier via CLI results in **zerotier-cli command not found**

Can't use it.

**Comment by cinghialino** [comment]
Please let me know of anything you'd need to help.

**Comment by joseph-henry** [comment]
What's the output of `ps aux | grep zero tier` ?

**Comment by joseph-henry** [comment]
Is there anything in `/var/lib/zerotier-one` ?

**Comment by cinghialino** [comment]
`ps aux | grep zerotier
root      2300  0.0  0.0  86428  3464 ?        Sl   14:44   0:00 /usr/local/zerotier/bin/zerotier-one -d
root      2303  0.1  0.0  11812  1684 ?        S    14:44   0:00 /bin/bash /usr/local/zerotier/bin/ztui_watchdog.sh -daemon
alessan+ 12170  0.0  0.0  23132   964 pts/13   S+   14:49   0:00 grep --color=auto zerotier`

**Comment by joseph-henry** [comment]
Do you have a `/dev/net/tun` ?

**Comment by cinghialino** [comment]
`/var/lib/zerotier-one$ ls -l
total 32
-rw------- 1 root root   24 Dec  5 14:44 authtoken.secret
drwx------ 2 root root 4096 Dec  5 14:44 controller.d
drwxr-xr-x 2 root root 4096 Dec  5 14:44 iddb.d
-rw-r--r-- 1 root root  141 Dec  5 09:57 identity.public
-rw------- 1 root root  270 Dec  5 09:57 identity.secret
-rw-r--r-- 1 root root  634 Dec  5 14:44 planet
-rw-r--r-- 1 root root    4 Dec  5 14:44 zerotier-one.pid
-rw-r--r-- 1 root root    4 Dec  5 14:44 zerotier-one.port`

**Comment by cinghialino** [comment]
`/dev/net$ ls -l
total 0
crw------- 1 root root 10, 200 Dec  5 10:25 tun`

**Comment by joseph-henry** [comment]
Hmm. Everything looks good so far. It's running, it has generated an identity, and has a TUN device available.

So when you open the GUI it doesn't show an ID in the bottom left corner?

**Comment by cinghialino** [comment]
[https://imgur.com/TjzVFu0](url) here is the interface. Inserting the Network ID and pressing Join has no effects

**Comment by joseph-henry** [comment]
I've updated the package to fix the `zerotier-cli: command not found issue`

https://download.zerotier.com/dist/zerotier-1.2.4-syn-avoton-6.1.spk?

Use that to see if you can tell any more about what's going on. Try stopping and restarting the package a few times and make sure its in the state you expect each time.

I'll keep thinking about this.

**Comment by cinghialino** [comment]
the new package has reinstated the `zerotier-cli: command not found` issue. 
Thank you so much. 

I will appreciate if you will update the package once you find a solution to the UX in DSM. Have a great week.

**Comment by joseph-henry** [comment]
When the GUI is unresponsive, try viewing the browser's console and see if there are any errors. That might be useful to check. And are you accessing this via http or https?

**Comment by cinghialino** [comment]
yes actually, a lot of errors! Accessing via https, self signed certificate.
opening Zerotier in the DSM results in this:
[https://pastebin.com/kCtA6J7k](url)
and also this: 
[https://pastebin.com/haUnWAxW](url)

**Comment by joseph-henry** [comment]
If anyone is still experiencing GUI problems can you provide me with the following information:

 - Browser (version if possible)
 - Specific errors from your Browser's console
 - Extensions installed (try disabling them to see if that helps)
 - Any information about how you're remotely connecting to your NAS
 - Whether you have a firewall enabled
 - Any non-default settings on the NAS

Thanks for your patience.
