### ISSUE TITLE
DS218+ (DSM 7) Invalid file format - Install zerotier

### ISSUE THREAD

**Issue by erkiki86** [zerotier/ZeroTierNAS#111]
Hello everybody. I have tried to install zerotier on my nas 218+ with dsm 7 and I have not been able to.

The procedure is: Package Center, manual installation, browse and choose the file "zerotier_apollolake-6.1_1.4.0-0.spk". I accept and it tells me the following:

Invalid file format. Contact the package developer. Down an ok button.

In version dsm 6.2 if I could install and use it.

I would appreciate being able to install it on my nas. Any solution?

Thank you.

**Comment by Mircc** [comment]
synology 220+ also has this problem in DSM7.0 RC version, looking forward to solving it

**Comment by softwareDoscar** [comment]
synology 218 also has this problem in DSM7.0 RC version, looking forward to solving it

**Comment by cpenzi** [comment]
Same issue. Zero-Tier package 1.4.0-0 is now "incompatible with DSM" and no longer works after upgrading to DSM 7.0. Trying to redownload it produces the same errors as others described. Looking forward to an update to support DSM 7.0 since it was officially released today 6/29/21

**Comment by joseph-henry** [comment]
Hey everyone. Thank you for your patience. We have new instructions for getting ZeroTier to work on Synology's latest DSM 7. Let me know if you have any trouble getting this to work.

https://docs.zerotier.com/devices/synology/
