### ISSUE TITLE
synology ds716ii

### ISSUE THREAD

**Issue by 414602845** [zerotier/ZeroTierNAS#13]
run on the nas  the Status show PORT_ERROR

**Comment by joseph-henry** [comment]
Is looks like that model uses the Intel (Braswell) architecture. Try downloading the [latest package](https://download.zerotier.com/dist/zerotier-1.2.4-syn-braswell-6.1.spk?pk_campaign=github_zerotiernas) (as of last night).

If it doesn't, make sure the daemon is running with `ps aux | grep zerotier`. Also, you can check for the presence of `/dev/net/tun`.

Let me know if that helps.

**Comment by 414602845** [comment]
thank you
