### ISSUE TITLE
QNAP TS-219P Support Request

### ISSUE THREAD

**Issue by bencevans** [zerotier/ZeroTierNAS#14]
From what I can find, all the QNAP packages available are x86 / 64. Would it be possible to add support for the TS-219P?

    [~] # uname -a
    Linux BITBAY 3.4.6 #1 Wed Dec 13 10:10:47 CST 2017 armv5tel unknown

**Comment by joseph-henry** [comment]
I will look into this. I have an ARM-based QNAP in the mail and will release some new packages soon.

**Comment by bencevans** [comment]
Following the [build instructions](https://github.com/zerotier/ZeroTierNAS/blob/master/QNAP/BUILD.md), I've got so far but missing the `linux/securebits` headers. Please, could you advise how you can get them? Nothing in the opkg repository seems to spring out.

```
[/share/homes/bencevans/src/ZeroTierOne] # make one ZT_QNAP=1
grep: invalid option -- r
BusyBox v1.01 (2017.12.12-18:06+0000) multi-call binary

Usage: grep [-ihHnqvs] PATTERN [FILEs...]

Search for PATTERN in each FILE or standard input.

Options:
        -H      prefix output lines with filename where match was found
        -h      suppress the prefixing filename on output
        -i      ignore case distinctions
        -l      list names of files that match
        -n      print line number with output lines
        -q      be quiet. Returns 0 if result was found, 1 otherwise
        -v      select non-matching lines
        -s      suppress file open/read error messages

g++ -O3 -fstack-protector -Wall -Wno-unused-result -Wreorder -fPIE -std=c++11 -pthread  -DNDEBUG -D_FORTIFY_SOURCE=2 -DZT_USE_MINIUPNPC -DMINIUPNP_STATICLIB -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DOS_STRING=\"Linux\" -DMINIUPNPC_VERSION_STRING=\"2.0\" -DUPNP_VERSION_STRING=\"UPnP/1.1\" -DENABLE_STRNATPMPERR -DZT_NO_TYPE_PUNNING -DZT_BUILD_PLATFORM=1 -DZT_BUILD_ARCHITECTURE=3 -DZT_SOFTWARE_UPDATE_DEFAULT="\"disable\"" -DZT_USE_ARM32_NEON_ASM_SALSA2012   -c -o one.o one.cpp
one.cpp:54:30: fatal error: linux/securebits.h: No such file or directory
 #include <linux/securebits.h>
                              ^
compilation terminated.
make: *** [<builtin>: one.o] Error 1
```

**Comment by joseph-henry** [comment]
I think my instructions might be ambiguous, but I'd recommend building on a separate machine using a cross compiler and then copying the resultant binary into the build directory on the QNAP device *then* building the package on the device.

Try stripping the binary (built for ARMv5TEL) out of this package: https://download.zerotier.com/dist/zerotier-1.2.4-syn-88f6281-6.1.spk

If that doesn't work we will need to use their special toolchains to cross-compile it.

**Comment by laomms** [comment]
need arm version for qnap too.
i got a arm version from http://pkg.entware.net/binaries/armv7/zerotier_1.1.14-4_armv7soft.ipk
but run error in my ts-231
it's show "zerotier-cli: missing port and zerotier-one.port not found in /opt/var/lib/zerotier-one"

**Comment by joseph-henry** [comment]
Thanks for your patience everyone. I've got a package to test: [https://download.zerotier.com/dist/zerotier_1.2.4-qnap-arm-x19.qpkg](https://download.zerotier.com/dist/zerotier_1.2.4-qnap-arm-x19.qpkg)

It's built for the armv5tel architecture and is a static build. I *think* this corresponds to QNAP's `arm-x19` designation (the names aren't directly correlated). The app will show up in QNAP's AppCenter but has no GUI for now.

Let me know if this works, and if it doesn't, what errors you receive.

Thanks!

**Comment by jcalavia** [comment]
Hi:

I've tried in a TS 419P-II with firmware 4.3.3.0404  and get the following output

```
Install QNAP package on TS-NAS...
./
./built_info
./qinstall.sh
./package_routines
./qpkg.cfg
52+1 records in
52+1 records out
1212+1 records in
1212+1 records out
package_routines: line 140: syntax error near unexpected token `}'
package_routines: line 140: `}'
package_routines: line 124: modprob: command not found
zerotier 1.2.4 is already installed. Setup will now perform package upgrading.
Firmware check is fine.
killall: zerotier-one: no process killed
Link service start/stop script: zerotier.sh
Set QPKG information in /etc/config/qpkg.conf
package_routines: line 140: syntax error near unexpected token `}'
package_routines: line 140: `}'
[App Center] ZeroTier 1.2.4 has been installed in /share/MD0_DATA/.qpkg/zerotier successfully.
[App Center] ZeroTier enabled.
[~] # zerotier-cli join XXXXXXXXXX
FATAL: kernel too old
Aborted
```

**Comment by joseph-henry** [comment]
@jcalavia Thanks for the test, I'll have another update for you guys to try shortly. How did you install this? Via the command line? I don't see where in the QNAP docs is shows how to do that. I'm curious because I don't yet know how to get this level of detail for the logs.

Also, what kernel version do you have? You can find this out with `uname -v`

**Comment by joseph-henry** [comment]
Going to build a static binary for kernel series `3.2.X`, I think that might work.

**Comment by joseph-henry** [comment]
@jcalavia Try the latest qpkg here: https://download.zerotier.com/dist/zerotier_1.2.4-qnap-arm-x19.qpkg

**Comment by bencevans** [comment]
I've installed `v01.2.4` from https://github.com/zerotier/download.zerotier.com/raw/master/htdocs/RELEASES/1.2.4/dist/zerotier_1.2.4-qnap-arm-x19.qpkg as the download.zerotier.com link no longer works.

Installation through the QNAP App Store GUI appeared successful.

After ssh'ing in and executing `zerotier-cli` I get the same as @joseph-henry:

```
[~] # zerotier-cli
zerotier-cli: missing port and zerotier-one.port not found in /share/MD0_DATA/.qpkg/zerotier
```

Digging into the `/share/MD0_DATA/.qpkg/zerotier` dir...

```
[/share/MD0_DATA/.qpkg/zerotier] # ./zerotier.sh
Usage: ./zerotier.sh {start|stop|restart}
[/share/MD0_DATA/.qpkg/zerotier] # ./zerotier.sh start
modprobe: could not parse modules.dep

ln: /usr/sbin/zerotier-cli: File exists
ln: /usr/bin/zerotier-cli: File exists
zerotier is disabled.
[/share/MD0_DATA/.qpkg/zerotier] # ./zerotier.sh stop
killall: zerotier-one: no process killed
[/share/MD0_DATA/.qpkg/zerotier] # ./zerotier.sh start
modprobe: could not parse modules.dep

ln: /usr/sbin/zerotier-cli: File exists
ln: /usr/bin/zerotier-cli: File exists
zerotier is disabled.
[/share/MD0_DATA/.qpkg/zerotier] # ./zerotier-one -d
[/share/MD0_DATA/.qpkg/zerotier] # terminate called after throwing an instance of '__gnu_cxx::__concurrence_broadcast_error'
  what():  __gnu_cxx::__concurrence_broadcast_error

[/share/MD0_DATA/.qpkg/zerotier] #
```

`uname -a`:

```
[/share/MD0_DATA/.qpkg/zerotier] # uname -a
Linux NAS 3.4.6 #1 Mon Apr 2 10:42:41 CST 2018 armv5tel unknown
```

**Comment by denniskavadas** [comment]
should we be able to connect to the web interface on our qnap on teh ZT ipaddress once zerotier is installed and running ?

**Comment by canghaiwuhen** [comment]
zerotier-cli: missing port and zerotier-one.port not found in /share/MD0_DATA/.qpkg/zerotier

**Comment by mlamie** [comment]
> I've installed `v01.2.4` from https://github.com/zerotier/download.zerotier.com/raw/master/htdocs/RELEASES/1.2.4/dist/zerotier_1.2.4-qnap-arm-x19.qpkg as the download.zerotier.com link no longer works.
> 
> Installation through the QNAP App Store GUI appeared successful.
> 
> After ssh'ing in and executing `zerotier-cli` I get the same as @joseph-henry:
> 
> ```
> [~] # zerotier-cli
> zerotier-cli: missing port and zerotier-one.port not found in /share/MD0_DATA/.qpkg/zerotier
> ```
> Digging into the `/share/MD0_DATA/.qpkg/zerotier` dir...
> 
> ```
> [/share/MD0_DATA/.qpkg/zerotier] # ./zerotier.sh
> Usage: ./zerotier.sh {start|stop|restart}
> [/share/MD0_DATA/.qpkg/zerotier] # ./zerotier.sh start
> modprobe: could not parse modules.dep
> 
> ln: /usr/sbin/zerotier-cli: File exists
> ln: /usr/bin/zerotier-cli: File exists
> zerotier is disabled.
> [/share/MD0_DATA/.qpkg/zerotier] # ./zerotier.sh stop
> killall: zerotier-one: no process killed
> [/share/MD0_DATA/.qpkg/zerotier] # ./zerotier.sh start
> modprobe: could not parse modules.dep
> 
> ln: /usr/sbin/zerotier-cli: File exists
> ln: /usr/bin/zerotier-cli: File exists
> zerotier is disabled.
> [/share/MD0_DATA/.qpkg/zerotier] # ./zerotier-one -d
> [/share/MD0_DATA/.qpkg/zerotier] # terminate called after throwing an instance of '__gnu_cxx::__concurrence_broadcast_error'
>   what():  __gnu_cxx::__concurrence_broadcast_error
> 
> [/share/MD0_DATA/.qpkg/zerotier] #
> ```
> `uname -a`:
> 
> ```
> [/share/MD0_DATA/.qpkg/zerotier] # uname -a
> Linux NAS 3.4.6 #1 Mon Apr 2 10:42:41 CST 2018 armv5tel unknown
> ```

I have the same issue. Any solution yet?

**Comment by bish0polis** [comment]
> I've installed v01.2.4 from https://github.com/zerotier/download.zerotier.com/raw/master/htdocs/RELEASES/1.2.4/dist/zerotier_1.2.4-qnap-arm-x19.qpkg as the download.zerotier.com link no longer works.

That one's dead too.

**Comment by nafai** [comment]
So I was able to get ZeroTier 1.4.6 working on a TS-220 (armv5tel 88F6282).

Unfortunately I don't have exact steps, because I had a lot of false starts with old versions, cluttered files in my qpkg directory, etc. So here's the result of what did end up working for me:

- Install from official qpkg, which won't work. But I work out of the .qpkg/zerotier directory, supporting files, and init script
- Go to http://bin.entware.net/armv5sf-k3.2/
- Get the ZT binary from there, then I used 7-Zip to pull out the binary. Replaced zerotier-one on the NAS with it
- You'll also need to get the supporting libraries libminiupnpc and libnatpmp from that same page.

With those supporting libraries, you _may_ be able to install them with opkg, but I did it differently-- because I was replacing a bunch of libraries on my own system, I kept a local lib directory I threw everything in (/share/MD0_DATA/.pkg/zerotier/lib) and modified the scripts to specify LD_LIBRARY_PATH explicitly. 

So I don't know what's necessary for a fresh start-- but here's what I've got in those scripts:

Modification to zerotier.sh start):
`LD_LIBRARY_PATH="/share/MD0_DATA/.qpkg/zerotier/lib/" $QPKG_ROOT/zerotier-one $QPKG_ROOT -d`

I also made this zerotier-cli.sh and pointed the symlink /usr/bin/zerotier-cli to it:
```
#!/bin/bash
LD_LIBRARY_PATH="/share/MD0_DATA/.qpkg/zerotier/lib/" /share/MD0_DATA/.qpkg/zerotier/zerotier-one -q -D"/share/MD0_DATA/.qpkg/zerotier/" $1 $2 $3 $4
```

Hope this helps someone else.
