### ISSUE TITLE
QNAP TS-831x Rejects x86 code

### ISSUE THREAD

**Issue by zurichawes** [zerotier/ZeroTierNAS#15]
Just bought this new NAS, a QNAP TS-831x.  It won't load the x86 code telling me the platform is incompatible.  It's got an Alpine AL-314 Quad-core 1.7 GHz Cortex-A15 processor.  Whereas my other QNAP TS-453BT3 has a Celeron chip and gave me no hassle.  Thoughts?

**Comment by sbilly** [comment]
You can build from source. https://github.com/zerotier/ZeroTierNAS/blob/master/QNAP/BUILD.md

**Comment by zurichawes** [comment]
Thanks, sbilly!  I'll try it out.

**Comment by joseph-henry** [comment]
@zurichawes Sorry for the late reply, but I would try: http://download.zerotier.com/RELEASES/1.2.12/dist/ZeroTier_1.2.12_arm-x41.qpkg

The TS-831X has a dual core Cortex-A15 (which is 32-bit). I've tested this package on the TS-231PII which has a quad core arrangement of the same core type so I'm hoping it will work for you.

And, thanks for chiming in @sbilly 

New packages for 1.4.0 are in the works.
