### ISSUE TITLE
Zerotier on Synology RS814 won't go online or join network

### ISSUE THREAD

**Issue by kapn1966** [zerotier/ZeroTierNAS#16]
Having a very similar issue to https://github.com/zerotier/ZeroTierNAS/issues/7 with a Synology RS814. It's an ARM architecture as well and the ZeroTier client never goes online. Using Firefox 58.0.2 but it seems more of a Synology ARM issue as the Intel Synology I have as well on the same network works fine.

![36805738-2ff5f016-1c8c-11e8-89ad-fce9e842a9a2](https://user-images.githubusercontent.com/36196908/36859940-00bdb546-1d4e-11e8-87fe-074e18b283dd.png)
![36805737-2fe35992-1c8c-11e8-86f2-e4ad2c3936e7](https://user-images.githubusercontent.com/36196908/36859941-00d3c2b4-1d4e-11e8-9da6-5d1e2f52d3b6.png)

Following the notes in the case I mention above, I checked for running processes and a log file.

I don't seem to have a watchdog process:
`admin@ht-nas02:/$ ps aux | grep zerotier`
`root     12795 92.1  0.1   4244   920 ?        R    12:49  23:17 /usr/sbin/zerotier-one -d`
`admin    16334  0.0  0.1   4648   796 pts/1    S+   13:15   0:00 grep --color=auto zerotier`
I have the tun device.

Haven't found the log file--it's not where I would expect. Using `find . -name zerotier*` from the / has revealed nothing obvious.

**Comment by kapn1966** [comment]
Also doesn't work on a DS214. Guessing this is really an ARM or Marvell issue.
![screenshot-2018-3-1 ht nas02](https://user-images.githubusercontent.com/36196908/36860468-518bc78c-1d4f-11e8-9a10-584177c39ab5.png)

**Comment by kapn1966** [comment]
I see that if I drill through on your forums there are architecture specific packages. Will try there.

**Comment by kapn1966** [comment]
After running the find again on the ds214, I've found a log file.
synoservice reports zerotier running. I seem to be able to start stop and restart without error.

However, the log file only shows the stopping. 
`Thu Mar  1 12:59:49 EST 2018 INSTALL: Unpacked to:  /volume2/@appstore/zerotier
Thu Mar  1 12:59:49 EST 2018 INSTALL: INSTALL_DIR= /usr/local/
Thu Mar  1 12:59:50 EST 2018 INSTALL: creating symlinks from /volume2/@appstore/zerotier to /usr/local/ and /usr/local//bin
Thu Mar  1 12:59:50 EST 2018 INSTALL: setting nginx reverse proxy config
Thu Mar  1 12:59:50 EST 2018 INSTALL: creating /dev/net/tun device
Thu Mar  1 12:59:50 EST 2018 INSTALL: loading TUN kernel module
Thu Mar  1 13:14:38 EST 2018 Stopping ZeroTier
Thu Mar  1 13:14:38 EST 2018 Stopping daemon watchdog
Thu Mar  1 13:14:38 EST 2018 Stopped ZeroTier
Thu Mar  1 13:20:44 EST 2018 Stopping ZeroTier
Thu Mar  1 13:20:44 EST 2018 Stopping daemon watchdog
Thu Mar  1 13:20:44 EST 2018 Stopped ZeroTier
`

**Comment by joseph-henry** [comment]
After starting can you check `ps aux | grep zerotier` and check that the service is running?

If not, can you run the `/usr/local/bin/zerotier-one` binary manually without error? If so it might just be an issue with the `start-stop-status.sh` script.

And as far as we can tell it's only an issue with the `Marvell XP` models?

**Comment by kapn1966** [comment]
The service is running:
`root      5842 99.6  0.1  19088  1444 ?        R    Feb28 9880:57 /usr/sbin/zerotier-one -d`
though there is no watchdog process.
So far as I can tell this is just a Marvell XP problem.

**Comment by kapn1966** [comment]
Any thoughts or things I can look at that might reveal what's up?

**Comment by joseph-henry** [comment]
Hmm. See what happens when you `echo "9993" > /var/lib/zerotier-one/zerotier-one.port` and then try to re-run the `zerotier-cli`

It could be that the service is running, but the CLI and the GUI are borked.

This is *not* a solution, but might get it to work. I am very puzzled as to why it isn't able to create that file. I'm actually looking into a similar behavior on ARM-based QNAP systems as well.

**Comment by kapn1966** [comment]
Well, we have a new error:
`ash-4.3# echo "9993" > /var/lib/zerotier-one/zerotier-one.port`
`ash-4.3# zerotier-cli`
`zerotier-cli: missing authentication token and authtoken.secret not found (or readable) in /var/lib/zerotier-one`

Is that useful?

**Comment by kapn1966** [comment]
There is indeed no `authtoken.secret` in that directory:
`ash-4.3# ls -l /var/lib/zerotier-one/`
`total 8`
`lrwxrwxrwx 1 root root   44 Feb 28 13:21 zerotier-cli -> /volume1/@appstore/zerotier/bin/zerotier-one`
`lrwxrwxrwx 1 root root   44 Feb 28 13:21 zerotier-idtool -> /volume1/@appstore/zerotier/bin/zerotier-one`
`lrwxrwxrwx 1 root root   44 Feb 28 13:21 zerotier-one -> /volume1/@appstore/zerotier/bin/zerotier-one`
`-rw-r--r-- 1 root root    5 Mar 14 14:07 zerotier-one.port`
`-rwxr-xr-x 1 root root 2914 Feb 28 13:21 ztui_watchdog.sh`

**Comment by joseph-henry** [comment]
For some reason it seems it can write all of the necessary files to its install directory with the exception of `authtoken.secret` and `zerotier-one.port`.

Can you issue `./zerotier-one -p5555 /var/lib/zerotier-one-test -d` (pick a port number you know is free). This will just start another instance but on port `5555` and store new files in a different path. And then inspect the directory `/var/lib/zerotier-one-test`? Kill that daemon after 30 seconds or so.

I'm curious if the lack of these files is an artifact of the install process.

**Comment by sijnak** [comment]
Hello, I have a few symptoms in common: the GUI shows that it never connects and other things. However the service is actually running and can be reached with `sudo zeortier-cli`

I'm not sure my case fits in this issue, but just in case, I mention it. My device is the 416play.

**Comment by joseph-henry** [comment]
@sijnak Are you connecting via Synology QuickConnect? There are known issues with that. Try using the GUI when you can connect locally. Then once it's set up you should be able to use it as you normally would via your ZeroTier IP address.

Let me know if that doesn't resolve the issue?

**Comment by sijnak** [comment]
I'm not using QuickConnect but always reaching the NAS from the local network or a ZeroTier network. In both cases, the GUI allways show "offline".

**Comment by joseph-henry** [comment]
Hmm. When using the CLI can you successfully join networks and at least reach your NAS via the ZT IP?

**Comment by dogoepp** [comment]
Yes. It's currently active. I didn't reboot since I joined the network, though.

**Comment by kapn1966** [comment]
Sorry for the delay and thank you for your ongoing assistance. I ran the temporary instance at port 5555 as suggested. The directory was created and the process appeared, but neither it nor the default port are visible to netstat (at least not when filtered for "LISTENING"). The only file to be created in the new directory was the pid file. I'm guessing you were expecting more. I did all of this as root and I paste the commands and output below.

`root@WACCFS01:~#  zerotier-one -p5555 /var/lib/zerotier-one-test -d`

`root@WACCFS01:~# ps aux | grep zero`
`root      5842 99.8  0.1  19088  1336 ?        R    Feb28 31464:39 /usr/sbin/zerotier-one -d`
`root     16663 99.8  0.3  19088  3904 pts/7    R    10:45   1:01 zerotier-one -p5555 /var/lib/zerotier-one-test -d`
`root     16702  0.0  0.0   4652   796 pts/7    S+   10:46   0:00 grep --color=auto zero`

`root@WACCFS01:~# netstat -an | grep "LISTEN "`
`tcp        0      0 0.0.0.0:161             0.0.0.0:*               LISTEN`
`tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN`
`tcp        0      0 0.0.0.0:5001            0.0.0.0:*               LISTEN`
`tcp        0      0 0.0.0.0:554             0.0.0.0:*               LISTEN`
`tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN`
`tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN`
`tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN`
`tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN`
`tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN`
`tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN`
`tcp6       0      0 :::161                  :::*                    LISTEN`
`tcp6       0      0 :::5000                 :::*                    LISTEN`
`tcp6       0      0 :::6281                 :::*                    LISTEN`
`tcp6       0      0 :::5001                 :::*                    LISTEN`
`tcp6       0      0 :::139                  :::*                    LISTEN`
`tcp6       0      0 :::80                   :::*                    LISTEN`
`tcp6       0      0 :::22                   :::*                    LISTEN`
`tcp6       0      0 :::443                  :::*                    LISTEN`
`tcp6       0      0 :::445                  :::*                    LISTEN`

`root@WACCFS01:~# ls -l /var/lib/zerotier-one-test/`
`total 4`
`-rw-r--r-- 1 root root 5 Mar 22 10:45 zerotier-one.pid`

**Comment by sijnak** [comment]
@joseph-henry, Yes. It's even currently active. I didn't reboot since I joined the network, though.

**Comment by joseph-henry** [comment]
Yes @sijnak, that would be great. I believe it is a separate issue.

**Comment by kapn1966** [comment]
Hi @joseph-henry , just wondering if you saw my post above and if you had any further thoughts of things I might do to resolve it or to shed more light on the problem.

**Comment by kapn1966** [comment]
@joseph-henry is there anyway I can manually generate those missing files?

**Comment by kapn1966** [comment]
Hi @joseph-henry , just wondering if you have any thoughts on what I can try to further diagnose or workaround?

**Comment by kapn1966** [comment]
Sigh. I guess I'm on my own. @joseph-henry I miss you.

**Comment by bjeanes** [comment]
Came here as my Synology is also reporting OFFLINE after a restart. `ps aux | grep zerotier` shows nothing.

Manually starting it with `/var/lib/zerotier-one/zerotier-one -d` does make it come online though. 

This is the first time I have restarted my NAS in a few months but this also happened last time. I don't remember what I did to get it back online last time, but it probably involved manually starting the service.

**Comment by bjeanes** [comment]
Clarification: The NAS joins the network and can be accessed from other devices on the network, but the UI _still_ reports OFFLINE regardless.

**Comment by joseph-henry** [comment]
Sorry I've a bit incommunicado lately, busy with some other features. I have updated the packages to reflect our new 1.2.8 release: https://download.zerotier.com/RELEASES/1.2.8/dist/ Only changes to the binary, nothing related to the GUI or start/stop/status script.

@kapn1966 I'm still at a complete loss for why those files would be missing, give the new package a try and let me know if anything changes. 

@bjeanes Which model do you have? Try the latest package linked above and let me know if that helps.

**Comment by kapn1966** [comment]
Thanks @joseph-henry 
you may not think you changed anything WRT to the setup on Armada, but it works right out of the box now. Thanks again!

**Comment by joseph-henry** [comment]
I'm really glad to hear that @kapn1966, thanks for helping us diagnose this problem anyway!
