### ISSUE TITLE
[Beta Testers Wanted] QNAP armv7l (arm-x41/cortex-a15) 

### ISSUE THREAD

**Issue by joseph-henry** [zerotier/ZeroTierNAS#17]
We now have a package for QNAP models which fit the designation `arm-x41`.

[https://download.zerotier.com/dist/zerotier_1.2.4_qnap-arm-x41.qpkg](https://download.zerotier.com/dist/zerotier_1.2.4_qnap-arm-x41.qpkg)

I've personally tested this on a `TS-231P2`. All of our packages will require that you first install `QVPN Service` before installing our package.

Packages for the rest of the ARM lineup are on their way. Thank you for your patience.

**Comment by herry1234** [comment]
installed on TS-231P.  it can be started, stoped but no UI to join, i mean doing nothing when clicking 'open'

**Comment by dpecak** [comment]
I have QNAP `TS-431` with armv7l, but zerotier_1.2.4_qnap-arm-x41.qpkg and zerotier_1.2.4-qnap-arm-x41.qpkg are not working (wrong architecture).

``
[~] # uname -a
Linux NAS 3.2.26 #2 SMP Tue Jul 10 06:38:03 CST 2018 armv7l unknown
``

**Comment by joseph-henry** [comment]
http://download.zerotier.com/RELEASES/1.2.12/dist/ZeroTier_1.2.12_arm-x41.qpkg Should work. Closing this issue but feel free to re-open it if there are issues.
