### ISSUE TITLE
Zerotier GUI on Synology shows offline

### ISSUE THREAD

**Issue by sijnak** [zerotier/ZeroTierNAS#18]
My Synology model: DS 416 play

the Zerotier GUI always shows this on my Synology Diskstation, despite it working from the command line (with `sudo zerotier-cli`). I am accessing this GUI through the web interface, either being connected to the same local network or through Zerotier.

![](https://user-images.githubusercontent.com/36196908/36859941-00d3c2b4-1d4e-11e8-9da6-5d1e2f52d3b6.png)

**Comment by cinghialino** [comment]
same problem (for quite some months) on DS1817+. the devs do not own every NAS equipment and they have different architecture, so the packets have limited testing. They try to help though!

**Comment by rfish001** [comment]
![image](https://user-images.githubusercontent.com/11706238/39079080-680984f8-4546-11e8-84df-a4e51bf08a56.png)
same problem on DS918+. （INTEL Celeron J3455）

**Comment by joseph-henry** [comment]
Can you show me the output from your browser's console after attempting to load the GUI? I'm interested in any errors you might see.

The only way we've been able to replicate this bug is by using Synology's QuickConnect. None of the devices we have exhibit this issue otherwise.

We do have a new batch of packages but only the binary has been updated, nothing related to the GUI or startup script: https://download.zerotier.com/RELEASES/1.2.8/dist/

**Comment by idealhack** [comment]
Same on DS916+ with ZeroTier 1.2.8

@joseph-henry I saw error logs in my console:

```
[Error] Failed to load resource: Could not connect to the server. (auth, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
[Error] Failed to load resource: Could not connect to the server. (status, line 0)
```

The address it trying to connect is `http://[zerotier_ip]:5000/auth?Cookie=id=[id]SynoToken=[token]`

**Comment by joseph-henry** [comment]
@idealhack Try the newest 1.2.10 packages (http://download.zerotier.com/dist/) there's a few fixes in there that might be relevant. And make sure you aren't using QuickConnect.

Also, does ZT work if you just use the command line interface `zerotier-cli` ?

Let me know if that doesn't fix the issue that you're seeing.

**Comment by idealhack** [comment]
@joseph-henry Same as 1.2.8 for me. Yes, the command line works fine.

**Comment by cinghialino** [comment]
same problem on a synology 1817+ avoton. the update did nothing for me (CLI works fine)

**Comment by joseph-henry** [comment]
Has anyone tried testing the GUI with QuickConnect disabled?

**Comment by microcai** [comment]
QuickConnect is disabled here, same problem. I'm using DS218j

**Comment by dogoepp** [comment]
I face the same issue and have had so for months. Is there any clue on the cause for it?

**Comment by bianwenbo** [comment]
Same issue. 
My current solution is to use the command line: `sudo zerotier-cli`
