### ISSUE TITLE
Requesting_configuration on Synology DS1517+

### ISSUE THREAD

**Issue by Kiwa21** [zerotier/ZeroTierNAS#19]
Install is going fine with zerotier-1.2.4-syn-avoton-6.1.spk
GUI is working fine but when joining a network system stays OFFLINE. and GUI shows that status staying at REQUESTING_CONFIGURATION.
If doing with the cli, got 200 join OK confirmation but still the zerotier-cli info says OFFLINE.

**Comment by joseph-henry** [comment]
What are the first digits of the network ID you're trying to join? Also, try upgrading to the latest package to see if that helps at all: https://download.zerotier.com/RELEASES/1.2.8/dist/

**Comment by Kiwa21** [comment]
Ok, so I installed the new 1.2.8 version.
The GUI isn't working yet.
I connect to SSH, then run zerotier-cli error saying : 
zerotier-cli: missing authentication token and authtoken.secret not found (or readable) in /var/lib/zerotier-one

I went to /var/lib/zerotier-one folder then ran : sudo chown +rwx authtoken.secret
Now zerotier-cli is running fine and I can join network from the command line !
Thanks for the fix @joseph-henry  :)

**Comment by carlyang1986** [comment]
I used 1.4 version for synology, it  works fine till reboot. After the NAS reboot, the status is offline, and GUI shows the status stay REQUESTING_CONFIGURATION. Another QNAP system does not have the problem.
