### ISSUE TITLE
Error running zerotier on a QNAP TS239 Pro II running 4.2.6 build 20170628

### ISSUE THREAD

**Issue by alrighte** [zerotier/ZeroTierNAS#2]
I installed the QPKG successfully but when i try and run the zerotier-cli I get the following
[/usr/lib] # zerotier-cli
zerotier-cli: /lib/libc.so.6: version `GLIBC_2.15' not found (required by zerotier-cli)
zerotier-cli: /lib/libc.so.6: version `GLIBC_2.7' not found (required by zerotier-cli)
zerotier-cli: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by zerotier-cli)
zerotier-cli: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by zerotier-cli)
zerotier-cli: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by zerotier-cli)
zerotier-cli: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by zerotier-cli)
zerotier-cli: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by zerotier-cli)

The versions the libs that are with QNAP are:
[/usr/lib] # strings /usr/lib/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_FORCE_NEW
[/usr/lib] # /lib/libc.so.6
GNU C Library stable release version 2.6.1, by Roland McGrath et al.
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2).
Compiled on a Linux >>2.6.22-14-server<< system on 2015-01-29.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.

I am running the latest version of the firmware from QNAP and I am unaware of any way to upgrade these libraries.
Any suggestions on how to fix this issues as im guessing this is going to be the same issues for every non 64bit systems.

Thanks

**Comment by joseph-henry** [comment]
We'll make a static build for this that won't require those shared libraries and try to get back to you soon. Thanks for the report!

**Comment by bitcloud** [comment]
any update on this?

**Comment by joseph-henry** [comment]
I'm revisiting this issue. From what I read the TS 239 Pro II uses the [Intel D410 Atom @ 1.66 GHz](https://ark.intel.com/products/43517/Intel-Atom-Processor-D410-512K-Cache-1_66-GHz) which is actually 64-bit. I'll make a static version and put it on our download page for you to test. 

In the meantime, just to verify can you post the output of `uname -a` ?

Thanks.

**Comment by czarau** [comment]
I have a TS-859U-RP+ with the same issue.
Linux srv-qnap 3.4.6 #1 SMP Tue Sep 5 12:17:06 CST 2017 x86_64 unknown

**Comment by czarau** [comment]
I finally got ZeroTier working on my TS-859U-RP+

1. http://pkg.entware.net/binaries/x86-64/ has the required dependancies

libstdcpp_6.3.0-6_x86-64/libstdc++.so.6.0.22
libc_2.23-6_x86-64/libm-2.23.so
libgcc_6.3.0-6_x86-64/libgcc_s.so.1

I placed the three files in /share/MD0_DATA/.qpkg/ZeroTier/lib64 and then created the following softlinks

ln -s libstdc++.so.6.0.22 libstdc++.so.6
ln -s libstdc++.so.6 libstdc++.so
ln -s libm-2.23.so libm.so.6 
ln -s libm.so.6 libm.so

Started ZeroTier-One with

LD_LIBRARY_PATH=/share/MD0_DATA/.qpkg/ZeroTier/lib64 /share/MD0_DATA/.qpkg/ZeroTier/zerotier-one /share/MD0_DATA/.qpkg/ZeroTier/ -d

LD_LIBRARY_PATH=/share/MD0_DATA/.qpkg/ZeroTier/lib64 /share/MD0_DATA/.qpkg/ZeroTier/zerotier-one -D$QPKG_ROOT -q join XXXXXXXX

This all worked except I could only ping the Qnap... SSH and Web Services where not responding.

/sbin/getbindaddr -refresh

Seemed to fix this issue.

**Comment by HarryKodden** [comment]
Confirmed. I have completed same solution on my QNAP TS459+ Pro. (x86_64 model) First install Entware-ng.qpkg via GUI manual install. Then copy the /share/MD0_DATA/.qpkg/Entware-ng/lib/ libraries over to your /share/MD0_DATA/.qpkg/ZeroTier/lib64 directory. Further steps as described above.
Well done 'czarau' !

**Comment by czarau** [comment]
Harry... I changed my ZeroTier.sh as per attached.
[ZeroTier.sh.txt](https://github.com/zerotier/ZeroTierNAS/files/1600145/ZeroTier.sh.txt)

**Comment by czarau** [comment]
And created a wrapper script for the client
[zerotier-cli.sh.txt](https://github.com/zerotier/ZeroTierNAS/files/1600150/zerotier-cli.sh.txt)
with a softlink in the same folder
ln -s zerotier-one zerotier-cli

**Comment by HarryKodden** [comment]
Yes, makes sense.
~~~
Good Job
~~~

**Comment by lifehome** [comment]
May I know is there a newer build available? As the problem seems still exists

**Comment by joseph-henry** [comment]
@lifehome I'm somewhat late on this, but I've built a new set of packages that should solve this issue but I don't have this device to test myself:

http://download.zerotier.com/RELEASES/1.2.12/dist/ZeroTier_1.2.12_x86_64.qpkg
http://download.zerotier.com/RELEASES/1.2.12/dist/ZeroTier_1.2.12_x86.qpkg

A 1.4.0 package will be released fairly soon as well.
