### ISSUE TITLE
There is not a download for Qnap arm-x31

### ISSUE THREAD

**Issue by emiliobarragan** [zerotier/ZeroTierNAS#21]
The link for download the file for qnap arm-x31    (ZeroTier_1.2.4-qnap-arm-x31.qpkg) doesn't work

**Comment by dpecak** [comment]
arm-x41 is doubled, no arm-x31

**Comment by paweljacewicz** [comment]
Any chance of getting a build for QNAP TS-431* ?

Thanks!

**Comment by joseph-henry** [comment]
Let me know whether these packages work for you guys:

http://download.zerotier.com/RELEASES/1.2.12/dist/ZeroTier_1.2.12_arm-x31.qpkg
http://download.zerotier.com/RELEASES/1.2.12/dist/ZeroTier_1.2.12_arm-x41.qpkg

I only have a TS-231PII to test on.

I'll have a set of 1.4.0 packages fairly soon as well.

**Comment by Nolperi** [comment]
The x31 package don't work for my TS-431. It says app is installed, but zerotie-cli is nowhere to be found. Console says the file does not exist
