### ISSUE TITLE
Server down...There is not a downloads at least QNAP qpkg downloads

### ISSUE THREAD

**Issue by Mrsusio** [zerotier/ZeroTierNAS#22]
Server down...There is not a downloads at least QNAP qpkg downloads

**Comment by joseph-henry** [comment]
I'm somewhat late on this, but new packages (`*.qpkg`) have been built for 1.2.12: http://download.zerotier.com/RELEASES/1.2.12/dist/

A 1.4.0 release for the same architectures will be available soon.
