### ISSUE TITLE
WD EX4 (details and problem)

### ISSUE THREAD

**Issue by michaelsmoody** [zerotier/ZeroTierNAS#24]
CPU on the EX4 shows as: Feroceon 88FR131 [56251311] revision 1 (ARMv5TE)

When installing the build for EX4, it shows "illegal instruction" when executing the commands. I suspect they're built for ARMv7?

I'll try all 3 available binaries, and see if there is any difference.

UPDATE: I also built it myself, same issue:

root@NAS / # zerotier-cli 
Illegal instruction

**Comment by sykosoft** [comment]
I'm wondering if this happens due to the pagesize on v4 firmware being 64k, whereas on v3 firmware, it was 4k? Perhaps recompilation is needed taking that into account....

**Comment by sykosoft** [comment]
@joseph-henry I noticed on a libzt issue you were offering to try to build a binary for someone. Would you be willing to look into this one?

**Comment by joseph-henry** [comment]
Hey @michaelsmoody, sorry it has taken me over a year to respond to your ticket. We don't get many ARMv5TE requests. I've tried to statically build a binary for another NAS platform and embed it in a WD package. Let me know if you get any milage out of this. If so, I'll build an official package with correct version info:

http://download.zerotier.com/dist/wd/WDMyCloudEX4_zerotier_1.4.2_armv5te.apkg
