### ISSUE TITLE
Launching installed app does nothing QNAP

### ISSUE THREAD

**Issue by jfeilbach** [zerotier/ZeroTierNAS#25]
Clicking on the installed package on my QNAP NAS launches the small window which has the second Open button on it. This button does nothing. There is nothing in the logs. All other apps launch fine. All browser plugins disabled. Same results on Chrome, Firefox and 

[https://i.imgur.com/x15q3nj.png](https://i.imgur.com/x15q3nj.png)

Model name	TS-879 Pro
Firmware version	4.3.4.0597 Build 20180528

Zerotier version 1.2.4
The installed file is ZeroTier_1.2.4_x86_64.qpkg downloaded from https://download.zerotier.com/RELEASES/1.2.4/dist/ZeroTier_1.2.4_x86_64.qpkg

From /etc/config/ qpkg.conf:
[ZeroTier]
Status = complete
Name = ZeroTier
Version = 1.2.4
Author = www.zerotier.com
QPKG_File = ZeroTier.qpkg
Date = 2018-06-14
Shell = /share/CACHEDEV1_DATA/.qpkg/ZeroTier/ZeroTier.sh
Install_Path = /share/CACHEDEV1_DATA/.qpkg/ZeroTier
RC_Number = 101
Enable = TRUE
Official = 0

In ssh shell into the NAS when I execute this command I get this result:
$ /share/CACHEDEV1_DATA/.qpkg/ZeroTier/ZeroTier.sh restart
ln: /usr/sbin/zerotier-cli: File exists
ln: /usr/bin/zerotier-cli: File exists

My install dir looks like this:
$ ls -la /share/CACHEDEV1_DATA/.qpkg/ZeroTier
total 1124
drwxr-xr-x  4   501             20    4096 2018-06-14 21:05 ./
drwxrwxrwx 11 admin administrators    4096 2018-06-14 18:02 ../
-rw-------  1 admin administrators      24 2018-06-14 17:32 authtoken.secret
drwx------  2 admin administrators    4096 2018-06-14 17:32 controller.d/
-rw-r--r--  1   501             20     120 2017-06-25 20:53 ._.DS_Store
-rw-r--r--  1   501             20    6148 2017-06-25 20:53 .DS_Store
-rw-r--r--  1   501             20       0 2017-05-31 01:18 .gitkeep
drwxr-xr-x  2 admin administrators    4096 2018-06-14 17:32 iddb.d/
-rw-r--r--  1 admin administrators     141 2018-06-14 17:32 identity.public
-rw-------  1 admin administrators     270 2018-06-14 17:32 identity.secret
-rw-r--r--  1 admin administrators     128 2018-06-14 17:37 .list
-rw-r--r--  1 admin administrators     634 2018-06-14 21:05 planet
-rw-r--r--  1   501             20    1853 2017-05-31 01:18 .qpkg_icon_80.gif
-rw-r--r--  1   501             20    1853 2017-05-31 01:18 .qpkg_icon.gif
-rw-r--r--  1   501             20    2375 2017-05-31 01:18 .qpkg_icon_gray.gif
-rwxr-xr-x  1 admin administrators     801 2018-06-14 17:37 .uninstall.sh*
-rwxr-xr-x  1   501             20 1071592 2017-06-25 20:50 zerotier-one*
-rw-r--r--  1 admin administrators       5 2018-06-14 21:05 zerotier-one.pid
-rw-r--r--  1 admin administrators       4 2018-06-14 21:05 zerotier-one.port
-rwxr-xr-x  1   501             20     731 2017-06-25 21:06 ZeroTier.sh*`

$ uname -a
Linux nas5 4.2.8 #1 SMP Mon May 28 09:37:00 CST 2018 x86_64 GNU/Linux

I have a 64-bit OS.

Any ideas or is everything done via cli?

**Comment by ericse** [comment]
You may try the zerotier-cli command line utility, it worked fine for me.

By the way, I installed from the qnapclub.eu repository, and while it is labeled 1.2.4 in the repo, internaly zerotier-cli report the version as 1.2.5

**Comment by joseph-henry** [comment]
Thanks for providing that advice, and yes a GUI is not supported on QNAP devices. The CLI is the recommended way for interacting with the service.
