### ISSUE TITLE
Synology DS413

### ISSUE THREAD

**Issue by tcurdt** [zerotier/ZeroTierNAS#26]
There is no official build for qoriq (ppc, freescale P1022, x13 Series) is there?
Would love to install it on my DS413 (synology_qoriq_413)

**Comment by joseph-henry** [comment]
@tcurdt What version of DSM are you running on that thing? I'm preparing a new batch of packages and can try to build something custom for you if you still need it.

**Comment by tcurdt** [comment]
DSM 6.2.1. Would be great - if it isn't too much work.

**Comment by joseph-henry** [comment]
I'm going to close this issue but feel free to re-open if the package isn't working as expected
