### ISSUE TITLE
Synology DS215j "join" has no effect

### ISSUE THREAD

**Issue by kwladyka** [zerotier/ZeroTierNAS#27]
https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
> DS215j - synology_armada375_215j

https://www.synology.com/en-us/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have
> DS215+ | Annapurna Labs Alpine AL-212 | Dual Core | 2 | Yes | Alpine4k | DDR3 1 GB

I installed the newest file from https://www.zerotier.com/download.shtml
> zerotier-1.2.8r0-syn-armada375-6.1.spk

When click "join" in zerotier app totally nothing happen. No error, no info, message etc. I wish it will give some error message.

PS WebBrowser Console has no error.

**Comment by kwladyka** [comment]
It works with `zerotier-cli` by SSH on Synology. I am connected but GUI is still blind and think I am offline.

GUI doesn't work.

**Comment by kwladyka** [comment]
I found this:

```
sudo zerotier-cli get XXX allowGlobal
Error connecting to the ZeroTier service: timed out

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
```

while

```
sudo zerotier-cli status
200 info a2de0c5ce7 1.2.8 ONLINE
```

```
sudo zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks XXX etingroup 6e:32:ee:9c:df:d4 OK PRIVATE eth50 YYY:0000:0000:0001/40,192.168.192.32/24
```

**Comment by joseph-henry** [comment]
Hello @kwladyka are you by chance using Synology's QuickConnect to remotely access your NAS? We are aware that some people use it and it has this effect.

**Comment by joseph-henry** [comment]
As a side note, do you mind listing the packages you currently have installed? We're unable to replicate this join button issue but we're thinking there might be some interaction with another package on the system.

**Comment by kwladyka** [comment]
Of course quickconnect is enabled.

Packages:
<img width="844" alt="screen shot 2018-07-12 at 00 00 16" src="https://user-images.githubusercontent.com/3903726/42601633-97044fbc-8566-11e8-9b84-c120deb765ed.png">

**Comment by kwladyka** [comment]
> you can still access the device's DSM GUI via the ZT address

Unfortunately I heard ZT stop works after each update, it is unstable etc. Too hight risk with unstable ZT. I can't disable quickconnect. BTW we need it for Cloud Station Server anyway.

CLI doesn't look like an option too, because:
https://github.com/zerotier/ZeroTierNAS/issues/27#issuecomment-401631664

**Comment by joseph-henry** [comment]
How often do you see the cli timing out like that? I assume that's the only issue you've had with it?

And you are correct that updating the DSM version does have non-deterministic effects on the ZT package sometimes.

**Comment by joseph-henry** [comment]
I've prepared a new set of packages (http://download.zerotier.com/dist/) for `1.2.12`. These contain patches to the core service as well as the bug that you found in the `get` command. Additionally it should work with whatever you set your web port to be (whereas the previous version was limited to 5000 or 5001).

Let me know if you have any issues with this new package. Hopefully it will be more reliable.
