### ISSUE TITLE
Synology Nas'es lose virtual interface address after reboot.

### ISSUE THREAD

**Issue by freekdegreef** [zerotier/ZeroTierNAS#28]
I have 3 different Synology Nas units with this same issue:
- DS916+
- DS1718
- DS212J

After a reboot these devices lose their virtual interface mac address, which re-lists them (un-authorized) on their respective ZeroTier networks. They are running version 1.2.8 and DSM 6.2

On Reddit somebody suggest I'd submit a issue here and suggested it might be deleting it's identity after a reboot?

**Comment by joseph-henry** [comment]
Hello @freekdegreef it shouldn't be deleting its identity on reboot but I won't rule out that possibility. 

Can you check your `/var/lib/zerotier-one` directory? You should see something like the following:

```
-rw------- 1 root   24 May  4 17:30 authtoken.secret
drwx------ 4 root 4096 May  4 17:30 controller.d
-rw-r--r-- 1 root  141 Dec  4  2017 identity.public
-rw------- 1 root  270 Dec  4  2017 identity.secret
drwxr-xr-x 2 root 4096 May  4 17:32 networks.d
drwxr-xr-x 2 root 4096 Jun 21 01:12 peers.d
-rw-r--r-- 1 root  634 May  4 17:30 planet
-rw-r--r-- 1 root    6 May 31 18:10 watchdog.pid
-rw-r--r-- 1 root    4 May 31 18:10 zerotier-one.port
```

**Comment by joseph-henry** [comment]
As a test I've uninstalled an older version `1.2.5` from home machine, installed `1.2.8r0`, rebooted, updated DSM to `6.2-23739` and rebooted a few times, everything including the identity files are still in place.

It is worth noting that after an install of a new version of ZT it will erase your `/var/lib/zerotier-one/network.d` so you will need to manually re-join your networks.

Can you list the packages you have installed on your devices? I'm thinking there might be some sort of interaction with something else.

**Comment by kennethkalmer** [comment]
I don't know how much help this is, but I saw this happen on a DS215j.

I was on DSM 6.1-_something_ when I installed 1.2.8r0 for the first time, and after upgrading to DSM 6.2-23739 it also lost the network and/or node address. However, there was an immediate update available (DSM 6.2-23739 Update 2), which I installed again and rebooted and the network configs persisted just fine afaict.

I'm brand new to ZeroTier, and being able access my Synology without QuickConnect and/or port-forwarding is a breath of fresh air.

**Comment by joseph-henry** [comment]
I can't reliably reproduce this issue, but I've uploaded a new set of packages for `1.2.12`. This new version will remove identity files upon uninstallation so make sure you back those up somewhere: http://download.zerotier.com/dist/

Let me know if either of you are still experiencing issues and I can take another look.

**Comment by ajayjohn** [comment]
I came here from https://www.reddit.com/r/zerotier/comments/8xnpeo/synology_changes_interface_address_after_reboot/ and I have the same issue too.
Post reboot, the Synology ZT ID changes and then I have to reauthorize the device to let it connect to my network again. Please let me know if there is any additional information that I can provide.

**Comment by joseph-henry** [comment]
@ajayjohn, Which version of the package are you using? Try the latest here: 
http://download.zerotier.com/dist/

You can expect the package to remove your identity files on uninstall but it should never do that on reboot. Let me know if you still see this issue with the `1.2.12` package.

**Comment by ajayjohn** [comment]
@joseph-henry The latest version seems like it does not lose the ZT ID. So that issue is probably fixed. Thanks!
However, now ZT starts up with a PORT_ERROR and leaving the network and joining it again does not seem to fix it. Any suggestions?

**Comment by rjbaat** [comment]
I have installed the latest beta: zerotier-1.2.12r1-syn-apollolake-6.1.spk and have the same problem on 2x 418play.
i get the message: zerotier-cli: missing port and zerotier-one.port not found in /var/packages/zerotier/target/var 

The package form the site 1.2.8 was giving me the problem that on reboot the id was changing and i had to reauthorise the device on the network.

**Comment by ajayjohn** [comment]
> @joseph-henry The latest version seems like it does not lose the ZT ID. So that issue is probably fixed. Thanks!
> However, now ZT starts up with a PORT_ERROR and leaving the network and joining it again does not seem to fix it. Any suggestions?
> 
> Edit: running sudo ls /dev/net/ gives me ls: cannot access /dev/net/: No such file or directory

Unfortunately, the current latest version still does not have the issue resolved :(
Wondering if development has paused on the NAS builds.

**Comment by elsurudo** [comment]
Having the same issue on DS218j w/ zerotier-1.2.8r0-syn-armada38x-6.1.spk – does anyone have a workaround?

**Comment by zhongyb** [comment]
Follow [this link ](https://ruimarinho.github.io/post/fix-tun-tap-not-available-on-a-synology-nas/)can fix this problem

**Comment by alatteri** [comment]
> @ajayjohn, Which version of the package are you using? Try the latest here:
> http://download.zerotier.com/dist/
> 
> You can expect the package to remove your identity files on uninstall but it should never do that on reboot. Let me know if you still see this issue with the `1.2.12` package.

Using the latest packages available, I am getting the PORT_ERROR on 3 different Synology NAS.

RS819
Realtek RTD1296 SoC
DSM 6.2.2-24922

RS816
MARVELL Armada 385 88F6820
DSM 6.2.2-24922

DS1511+
INTEL Atom D525
DSM 6.2.2-24922

**Comment by mrschwarz50** [comment]
> Follow [this link ](https://ruimarinho.github.io/post/fix-tun-tap-not-available-on-a-synology-nas/)can fix this problem

I had the same problem (PORT_ERROR) with a DS218j after uninstalling and reinstalling the Zerotier package. I followed the instructions at the above link and resolved the problem. I had to log in as root and used the same password as the admin account. Using the admin account wouldn't work.

I have restarted the NAS 3 times and the connection is stable.

**Comment by TGeRi** [comment]
The fix on the link works like a charm.
ZeroTier 1.2.13, Synology NAS, newest DSM!
THANK YOUR!

**Comment by joseph-henry** [comment]
Hey everyone, my apologies for taking so long on this. Here's an [updated set of packages](https://download.zerotier.com/PRERELEASES/1.4.0pre/synology) to preview `1.4.0`. It addresses the following issues:

 - Losing interface on reboot: `insmod /lib/modules/tun.ko` issued upon each reboot (and start of the service). See tickets #41 and #43 
 - Identity files moved to more traditional location `/var/lib/zerotier-one`, and are now preserved across uninstalls, reinstalls, updates, etc. Prior to this version, during uninstall we were intentionally deleting your identity files just for thoroughness but this seems to be annoying to most users (rightly so). So uninstalling and updating to this version is the last time that your configuration will get wiped. See tickets #41
 - Service script now sends proper SIGKILL signal
 - Segfault on ARM (*might* be fixed), see ticket #52
 - Memory leak (*might* be fixed), see ticket #46

To view logs for this package, see: `/var/log/packages/zerotier.log`

**Comment by rjbaat** [comment]
I installed the latest release version on a 418play. But after a reboot of the nas it is not working.
The cli gives me this error `missing authentication token and authtoken.secret not found (or readable) in /var/lib/zerotier-one`

**Comment by joseph-henry** [comment]
@rjbaat I would suggest trying the command as root. Otherwise it appears this issue was resolved. Re-open if I am mistaken.
