### ISSUE TITLE
DS415play Not work

### ISSUE THREAD

**Issue by mendezzz2** [zerotier/ZeroTierNAS#29]
Hi, I installed the zerotier evansport package on the nas DS415play; it installs correctly but does not execute JOIN network

**Comment by joseph-henry** [comment]
@mendezzz2 try turning off QuickConnect and make sure that your web port is 5000 or 5001 (Synology defaults). A future package will allow for custom ports.

**Comment by joseph-henry** [comment]
I've got a new batch of packages (http://download.zerotier.com/dist/), you can try the `evansport` or `x86`. This should allow you to use any port.
