### ISSUE TITLE
ZeroTier on DS414 missing in synoservice

### ISSUE THREAD

**Issue by jandanielcz** [zerotier/ZeroTierNAS#3]
I have installed ZeroTier One on my DS414:
`DS414 | Marvell Armada XP MV78230 | Dual Core | 2 | Yes | Armadaxp | DDR3 1 GB`

I have tried version for _DS413j_ processor was similar.

Web UI looks working, but stays offline. So I have checked logs and cli.

Cli:
`
zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one
`

According to googling, that means service is not running.
`sudo synoservice --list` does not show _zero*_ among installed packages.

Can I help somehow to make it work on this Synology?
Thanks

**Comment by jandanielcz** [comment]
Also ZeroTier is cosuming most of my processor power (see attached screenshot).
![2017-09-12 11_31_22-civic](https://user-images.githubusercontent.com/219847/30318693-1d7effe4-97ae-11e7-8cb1-44a92dde9ba1.png)

**Comment by joseph-henry** [comment]
What version of DSM are you running on your 414?

**Comment by ichris007** [comment]
@jandanielcz have you solve the problem of WEB UI offline?

**Comment by joseph-henry** [comment]
@ichris007 the web UI offline bug (or "join button doesn't work" problem) is due to unsupported processor architectures. If you can tell me what model you have I can add it to the queue and notify you when it's complete.

**Comment by rklomp** [comment]
Having the same issue in my DS214 (same CPU).
It is now running DSM 6.1.4-15217

My device was last seen online 15 days ago.

**Comment by dasmoover** [comment]
The Synology boards are ARMEL.

I have run into the same issue - it seems the prepackaged version does not work.

Zerotier installs on my Debian chroot that runs on an ARMEL boards (414, 214, 115, etc)

A fix would be nice.

**Comment by ichris007** [comment]
@joseph-henry Thanks for your reply. My Synology board model is MARVELL Armada 370. Looking forward to your update.

**Comment by thunfischbrot** [comment]
@joseph-henry Same issue here with a DS414j with a Mindspeed Comcerto 2000 ARMv7, C2200 (2C/2T).
If you would build for that arch it would make me very happy!

**Comment by emsigler** [comment]
+1 for support for the DS214 MARVELL Armada XP MV78230

**Comment by joseph-henry** [comment]
Thanks for having patience, everybody. I'm rolling out some experimental packages you can test.

@emsigler, @jandanielcz and @rklomp https://download.zerotier.com/dist/zerotier-1.2.4-syn-armadaxp-6.1.spk
@thunfischbrot https://download.zerotier.com/dist/zerotier-1.2.4-syn-armadaxp-6.1.spk
@ichris007 https://download.zerotier.com/dist/zerotier-1.2.4-syn-armada370-6.1.spk

@dasmoover Let me know exactly which models you have and I can get your some beta links to try

**Comment by emsigler** [comment]
@joseph-henry I installed the package on my DS214. Haven't had the chance to test extensively, but so for it seems to work well. Was able to connect and join a network. Thanks!

**Comment by rklomp** [comment]
Thanks @joseph-henry! It looks like it is working again with this new package

**Comment by thunfischbrot** [comment]
It's working on the DS414j, thank you!

**Comment by jdos77** [comment]
I installed the armada370/375 on my DS215j and it seems to work okay.

**Comment by ichris007** [comment]
@joseph-henry this still can not work, I will try to reinstall it.

**Comment by giucas-falchetto** [comment]
I tried the package zerotier-1.2.4-syn-armada370-6.1.spk on my DS213j but, when I open the app, zerotier remain OFFLINE and the process appears as suspended.
DS213j CPU is  MARVELL Armada 370 88F6707 and DSM version is 6.1.4-15217 Update 5
Any help would be appreciated

**Comment by joseph-henry** [comment]
If anyone is still experiencing GUI problems can you provide me with the following information:

 - Browser (version if possible)
 - Specific errors from your Browser's console
 - Extensions installed (try disabling them to see if that helps)
 - Any information about how you're remotely connecting to your NAS
 - Whether you have a firewall enabled
 - Any non-default settings on the NAS

Thanks for your patience.

**Comment by joseph-henry** [comment]
@giucas-falchetto Try the latest package (as of last night).

https://download.zerotier.com/dist/zerotier-1.2.4-syn-armada370-6.1.spk

**Comment by pierluigiconti** [comment]
Hi all, I have a DS218+ with apollolake

INTEL Celeron J3355
--

version DSM: 
DSM 6.1.4-15217 Update 5



but it seems not working, still remaining offline while clicking the join button.

I've used the zerotier's apollolake version: 

Intel Apollo Lake | zerotier-1.2.4-syn-apollolake-6.1.spk
-- | --


Browser Chrome, version 63.0.3239.132 


Thanks

**Comment by joseph-henry** [comment]
@pierluigiconti are you accessing your NAS via Synology's QuickConnect?

**Comment by pierluigiconti** [comment]
Hi Joseph,
yes I'm using quickconnect

**Comment by thunfischbrot** [comment]
Try using it via the local IP, not via quickconnect. It is working for me now, takes a minute until it changes from  OFFLINE to the real status.

**Comment by viliamr** [comment]
I installed zerotier-1.2.4-syn-armada38x-6.1.spk on my synology DS216j, the zero service is running but can't join network. :/
tried to connect to my DSM via ip address on local network, so i'm not using quickconnect.

tia

**Comment by viliamr** [comment]
problem solved. i installed the latest DSM version and now everything working great!

**Comment by joseph-henry** [comment]
Glad to hear @viliamr! Out of curiosity, which DSM version were you previously on?

Also take note that on some of the ARM-based devices it can take a little while to join networks sometimes.

**Comment by ohault** [comment]
For DS414 (Armada XP MV78230) does it possible to have a package published on https://download.zerotier.com/dist/synology/ ?

**Comment by rexxfan** [comment]
> For DS414 (Armada XP MV78230) does it possible to have a package published on https://download.zerotier.com/dist/synology/ ?

I'll second that. Please?

**Comment by miquelbotanch** [comment]
Any idea other package that could work on this device ? DS414

**Comment by idimou** [comment]
> > For DS414 (Armada XP MV78230) does it possible to have a package published on https://download.zerotier.com/dist/synology/ ?
> 
> I'll second that. Please?

Me too. I think the existing package does not work with DSM 6.2.
