### ISSUE TITLE
Synology web port

### ISSUE THREAD

**Issue by laduke** [zerotier/ZeroTierNAS#32]
Looked into this because of
zerotier/ZeroTierOne/issues/841

Looks like the http is hard-coded to 5000/5001? (And users can change their synology web port I guess) 

https://github.com/zerotier/ZeroTierNAS/blob/740b9b4595fee2e28f846ad4785ded009b98377b/Synology/package/zerotier/app/dsm/ZeroTierNode.jsx#L4

I could fix this up, but need a way to test that it works :)

**Comment by joseph-henry** [comment]
Using `window.location.port` now. Hopefully that should help.
