### ISSUE TITLE
QNAP arm-x31 packages

### ISSUE THREAD

**Issue by dpecak** [zerotier/ZeroTierNAS#33]
Packages for QNAP x31 models are missing from release download page ([https://download.zerotier.com/RELEASES/1.2.4/dist/](url)), but on webpage [https://github.com/zerotier/ZeroTierNAS/blob/master/QNAP/README.md](url) is a reference to `zerotier_1.2.4-qnap-arm-x31.qpkg` package.

Anyone have that package? I tried arm-x41 and it is not working.

**Comment by paweljacewicz** [comment]
Looking for the same version. Any help would be appreciated!

**Comment by joseph-henry** [comment]
Hey @dpecak and @paweljacewicz Give this package a try: http://download.zerotier.com/RELEASES/1.2.12/dist/ZeroTier_1.2.12_arm-x31.qpkg

**Comment by Nolperi** [comment]
You can get x31 version 1.2.12 from here: https://download.zerotier.com/dist/qnap/

But I can't get it to install correctly on my TS-431 (base model, not -K, -C, -P or +)

It does say install complete, app ready to use, and the app does appear in App Center. 
But typing zerotier-cli into command line results in: "command not found"
