### ISSUE TITLE
GUI desperatley needed for NASes

### ISSUE THREAD

**Issue by TheSandshark** [zerotier/ZeroTierNAS#35]
Since most commercial NAS users are not Linux users and shy away from any CLI use on the device, a NAS GUI is desperately needed to allow the majority to make use of this excellent tool.  It is unfortunate that the XeroTier developers went away from an HTML compatible interface that could be ported to the NAS environment.

Is anyone working with the ZeroTier team to develop a Linux GUI that can be utilized on a NAS?

**Comment by joseph-henry** [comment]
ZeroTier does provide a GUI for Synology packages, what other brands do you have in mind?

A Linux desktop GUI is something I've considered but each NAS manufacturer is their own special snowflake so a GUI that works everywhere isn't realistic.

**Comment by TheSandshark** [comment]
I have a ReadyNAS, but I think the statement goes for just about any NAS with the possible exception of FreeNAS, since those users are going to be to be Linux aware.  The old V1.1 GUI was adapted to the ReadyNAS and likely could have been for just about any NAS.  But it stopped working at V1.3 (or maybe 1.2).  So to say it's not realistic to have a common GUI is not well thought out.  It may be that the developers of ZeroTier have created an environment that has currently forced that to be the case, but that makes it their lack of vision that creates the issue, not a hard, insurmountable fact.  And that's why I suggested that work would need to be done with the ZeroTier developers -- to break down any barriers they have created.
Unfortunately, I'm not a developer.  But what is it about the Synology GUI that makes it unsuited for other NASes?  Does it actually **_run_** on the NAS?  An HTML/Java based GUI that just accesses a port on the NAS certainly makes a lot more sense for a headless device.  Even a compiled one that can be installed on a host would provide more access than the CLI for basic non Linux aware NAS users   How does one access the ZeroTier Edge?  Certainly they don't expect you to attach a monitor and keyboard to it.   Or is it also CLI only via SSH?
