### ISSUE TITLE
Better links for ReadyNAS

### ISSUE THREAD

**Issue by TheSandshark** [zerotier/ZeroTierNAS#36]
The link provided for the ReadyNAS is to the code, not the package.  Users not familiar with GitHub may have trouble navigating to the package.  There is also a newer fork for AMD64 systems:

Last version with GUI, only version for ARM -- old but still works: https://github.com/NAStools/zerotierone/releases/tag/readynas%2F1.1.14-nt3

Newer version for AMD64 only, no GUI:  https://github.com/didyouexpectthat/zerotierone/releases/tag/readynas%2F1.2.4-nt1-RC2

**Comment by joseph-henry** [comment]
Updated. Thank you.
