### ISSUE TITLE
QNAP TS-428 Support Request

### ISSUE THREAD

**Issue by sarices** [zerotier/ZeroTierNAS#39]
CPU: Realtek ARM CortexA53 (64-bit), RTD 1296, 1.4GHz

**Comment by joseph-henry** [comment]
@sarices Give this package a try: http://download.zerotier.com/RELEASES/1.2.12/dist/ZeroTier_1.2.12_arm_64.qpkg

**Comment by LucasD11** [comment]
Yes, it worked. But could you add it into the document?
