### ISSUE TITLE
build zerotier for MyCloudPR2100 

### ISSUE THREAD

**Issue by witwall** [zerotier/ZeroTierNAS#42]
I setup a docker(zerotier/zt1-build-fedora-22-x86-base) and then make bin for MyCloudPR2100

when run 

```
sh-4.3# ../mksapkg   -E -s -m MyCloudPR2100
```
got ,

```
============================================
        mksapkg version: v1.2
============================================
ERROR: fail to read apkg.rc file!

sh-4.3# ls
Apkg.rc    apkg.xml  clean.sh  install.sh  remove.sh  stop.sh
apkg.sign  bin       init.sh   preinst.sh  start.sh   webpage

```
![image](https://user-images.githubusercontent.com/3222056/51072732-49306e80-16a0-11e9-910a-4fdb1856d989.png)

then 
```
sh-4.3# cp Apkg.rc  apkg.rc
sh-4.3# ../mksapkg   -E -s -m MyCloudPR2100
```
succeed.

![image](https://user-images.githubusercontent.com/3222056/51072716-f9ea3e00-169f-11e9-8121-dc318b403bb0.png)

but when install it, just got error, 
![image](https://user-images.githubusercontent.com/3222056/51072748-c360f300-16a0-11e9-9387-50e57a17abd4.png)

without any detail error message.

**Comment by joseph-henry** [comment]
Hello @witwall, try this package: https://download.zerotier.com/RELEASES/1.2.12/dist/MyCloudPR2100_zerotier_1.2.12.apkg
