### ISSUE TITLE
DS3615 zero tier does not start after stop

### ISSUE THREAD

**Issue by helio58** [zerotier/ZeroTierNAS#43]
Hi have manage setup zerotier and connect to network .
Have to stop zerotier a couple of times. And now the service won't start.
I have uninstall and install several times but it will not start.
Here is the log

root@Syno:/usr/local/bin$ cat /var/log/zerotier-one.log
Wed Dec  5 11:45:38 CET 2018 INSTALL: Unpacked to:  /volume3/@appstore/zerotier
Wed Dec  5 11:45:38 CET 2018 INSTALL: INSTALL_DIR= /usr/local/
Wed Dec  5 11:45:38 CET 2018 INSTALL: creating symlinks from /volume3/@appstore/zerotier to /usr/local/ and /usr/local//bin
Wed Dec  5 11:45:38 CET 2018 INSTALL: setting nginx reverse proxy config
Wed Dec  5 11:45:38 CET 2018 INSTALL: creating /dev/net/tun device
Wed Dec  5 11:45:38 CET 2018 INSTALL: loading TUN kernel module
Wed Dec  5 11:45:39 CET 2018 Starting ZeroTier 
Wed Dec  5 11:45:39 CET 2018 Stopping daemon watchdog
Wed Dec  5 11:45:39 CET 2018 Starting daemon watchdog (to protect /dev/net/tun)
starting /usr/local/zerotier/bin/zerotier-one
Wed Dec  5 11:45:40 CET 2018 Started ZeroTier
Wed Dec  5 11:51:20 CET 2018 Stopping ZeroTier
Wed Dec  5 11:51:20 CET 2018 Stopping daemon watchdog
Wed Dec  5 11:51:20 CET 2018 Stopped ZeroTier
Thu Jan 31 19:16:14 CET 2019 Starting ZeroTier 
Thu Jan 31 19:16:14 CET 2019 Stopping daemon watchdog
Thu Jan 31 19:16:14 CET 2019 Starting daemon watchdog (to protect /dev/net/tun)
starting /usr/local/zerotier/bin/zerotier-one
Thu Jan 31 19:16:15 CET 2019 Started ZeroTier
Thu Jan 31 19:29:23 CET 2019 Stopping ZeroTier
Thu Jan 31 19:29:23 CET 2019 Stopping daemon watchdog
Thu Jan 31 19:29:23 CET 2019 Stopped ZeroTier
Thu Jan 31 19:30:19 CET 2019 Starting ZeroTier 
Thu Jan 31 19:30:19 CET 2019 Stopping daemon watchdog
Thu Jan 31 19:30:19 CET 2019 Starting daemon watchdog (to protect /dev/net/tun)
starting /usr/local/zerotier/bin/zerotier-one
Thu Jan 31 19:30:20 CET 2019 Started ZeroTier
Thu Jan 31 19:44:18 CET 2019 Stopping ZeroTier
Thu Jan 31 19:44:18 CET 2019 Stopping daemon watchdog
Thu Jan 31 19:44:18 CET 2019 Stopped ZeroTier
Thu Jan 31 19:44:26 CET 2019 UNINSTALL: killing zerotier-one and watchdog
Thu Jan 31 19:44:26 CET 2019 UNINSTALL: removing config files but leaving identity.* files
Thu Jan 31 19:44:26 CET 2019 UNINSTALL: removing old symlinks
Thu Jan 31 19:44:26 CET 2019 UNINSTALL: removing nginx reverse proxy config
Thu Jan 31 19:48:27 CET 2019 INSTALL: Unpacked to:  /volume3/@appstore/zerotier
Thu Jan 31 19:48:27 CET 2019 INSTALL: INSTALL_DIR= /usr/local/
Thu Jan 31 19:48:27 CET 2019 INSTALL: creating symlinks from /volume3/@appstore/zerotier to /usr/local/ and /usr/local//bin
Thu Jan 31 19:48:27 CET 2019 INSTALL: setting nginx reverse proxy config
Thu Jan 31 19:48:27 CET 2019 INSTALL: creating /dev/net/tun device
Thu Jan 31 19:48:27 CET 2019 INSTALL: loading TUN kernel module
Thu Jan 31 19:52:43 CET 2019 Stopping ZeroTier
Thu Jan 31 19:52:43 CET 2019 Stopping daemon watchdog
Thu Jan 31 19:52:43 CET 2019 Stopped ZeroTier
Thu Jan 31 20:01:39 CET 2019 Stopping ZeroTier
Thu Jan 31 20:01:39 CET 2019 Stopping daemon watchdog
Thu Jan 31 20:01:39 CET 2019 Stopped ZeroTier
Thu Jan 31 20:03:05 CET 2019 Stopping ZeroTier
Thu Jan 31 20:03:05 CET 2019 Stopping daemon watchdog
Thu Jan 31 20:03:05 CET 2019 Stopped ZeroTier
Thu Jan 31 20:03:17 CET 2019 UNINSTALL: killing zerotier-one and watchdog
Thu Jan 31 20:03:17 CET 2019 UNINSTALL: removing config files but leaving identity.* files
Thu Jan 31 20:03:17 CET 2019 UNINSTALL: removing old symlinks
Thu Jan 31 20:03:17 CET 2019 UNINSTALL: removing nginx reverse proxy config
Thu Jan 31 20:06:13 CET 2019 INSTALL: Unpacked to:  /volume3/@appstore/zerotier
Thu Jan 31 20:06:13 CET 2019 INSTALL: INSTALL_DIR= /usr/local/
Thu Jan 31 20:06:13 CET 2019 INSTALL: creating symlinks from /volume3/@appstore/zerotier to /usr/local/ and /usr/local//bin
Thu Jan 31 20:06:13 CET 2019 INSTALL: setting nginx reverse proxy config
Thu Jan 31 20:06:13 CET 2019 INSTALL: creating /dev/net/tun device
Thu Jan 31 20:06:13 CET 2019 INSTALL: loading TUN kernel module
Thu Jan 31 20:14:03 CET 2019 Stopping ZeroTier
Thu Jan 31 20:14:03 CET 2019 Stopping daemon watchdog
Thu Jan 31 20:14:03 CET 2019 Stopped ZeroTier
Thu Jan 31 20:14:03 CET 2019 UNINSTALL: killing zerotier-one and watchdog
Thu Jan 31 20:14:03 CET 2019 UNINSTALL: removing config files but leaving identity.* files
Thu Jan 31 20:14:03 CET 2019 UNINSTALL: removing old symlinks
Thu Jan 31 20:14:03 CET 2019 UNINSTALL: removing nginx reverse proxy config
Thu Jan 31 20:18:14 CET 2019 INSTALL: Unpacked to:  /volume3/@appstore/zerotier
Thu Jan 31 20:18:14 CET 2019 INSTALL: INSTALL_DIR= /usr/local/
Thu Jan 31 20:18:14 CET 2019 INSTALL: creating symlinks from /volume3/@appstore/zerotier to /usr/local/ and /usr/local//bin
Thu Jan 31 20:18:14 CET 2019 INSTALL: setting nginx reverse proxy config
Thu Jan 31 20:18:14 CET 2019 INSTALL: creating /dev/net/tun device
Thu Jan 31 20:18:14 CET 2019 INSTALL: loading TUN kernel module
Thu Jan 31 20:26:57 CET 2019 Stopping ZeroTier
Thu Jan 31 20:26:57 CET 2019 Stopping daemon watchdog
Thu Jan 31 20:26:57 CET 2019 Stopped ZeroTier
Thu Jan 31 20:27:04 CET 2019 UNINSTALL: killing zerotier-one and watchdog
Thu Jan 31 20:27:04 CET 2019 UNINSTALL: removing config files but leaving identity.* files
Thu Jan 31 20:27:04 CET 2019 UNINSTALL: removing old symlinks
Thu Jan 31 20:27:04 CET 2019 UNINSTALL: removing nginx reverse proxy config

Thanks

**Comment by joseph-henry** [comment]
Hey, my apologies for taking so long on this. Here's an [updated set of packages](https://download.zerotier.com/PRERELEASES/1.4.0pre/synology) to preview `1.4.0`. It addresses the following issues:

 - Losing interface on reboot: `insmod /lib/modules/tun.ko` issued upon each reboot (and start of the service). See tickets #41 and #43 
 - Identity files moved to more traditional location `/var/lib/zerotier-one`, and are now preserved across uninstalls, reinstalls, updates, etc. Prior to this version, during uninstall we were intentionally deleting your identity files just for thoroughness but this seems to be annoying to most users (rightly so). So uninstalling and updating to this version is the last time that your configuration will get wiped. See tickets #41
 - Service script now sends proper SIGKILL signal
 - Segfault on ARM (*might* be fixed), see ticket #52
 - Memory leak (*might* be fixed), see ticket #46

To view logs for this package, see: `/var/log/packages/zerotier.log`
