### ISSUE TITLE
ASUStor NAS Support

### ISSUE THREAD

**Issue by laduke** [zerotier/ZeroTierNAS#44]
A user asked about this platform. Posting here so it's more public. 

http://developer.asustor.com/

Not sure if it's possible; Looks like you need to log in to get any details.

**Comment by joseph-henry** [comment]
I can try to look into this, what model do you have? Since I don't have a device to test on I will need to send you a test package if that's alright.

**Comment by tuzzmaniandevil** [comment]
@joseph-henry Did this ever get done by chance? :-)

**Comment by edgard-arch** [comment]
hello could it be installed on asusor NAS?

**Comment by edgard-arch** [comment]
Did this ever get done by chance? please :( :(

**Comment by weiyideai520** [comment]
Is it available now?On the ASUSTOR NAS

**Comment by joseph-henry** [comment]
Good news, everyone!

I'd like to announce that I've finally gotten around to building an ASUStor APK and it's up for download. I'd regard it as BETA but it seems to work on my `x86-64` and `aarch64` boxes. It also should work with `i386` boxes. It contains binaries for all three architectures and will install the correct one for your machine. Hence the `_any` postfix.

You can get it here: https://download.zerotier.com/RELEASES/1.4.6/dist/asustor/

Additional information can be found in the ASUStor subfolder: https://github.com/zerotier/ZeroTierNAS/tree/master/asustor

Let me know how this works and if there's anything I can fix. It currently has no GUI so you'll have to enable SSH and use the CLI exclusively.

**Comment by ali-95** [comment]
_AS1004T v2_
ARMv7 Processor rev 1 (v7l)
install zerotier_1.4.6_any.apk 
```
zerotier-cli info 
-sh: zerotier-cli: not found
```

**Comment by crucialscott** [comment]
> _AS1004T v2_
> ARMv7 Processor rev 1 (v7l)
> install zerotier_1.4.6_any.apk
> [![zerotier-1-4-6-any.jpg](https://camo.githubusercontent.com/4a183eddb7e2f0df8e35da891864a1c85fc66dbbb804c797531e2e1588bf166b/68747470733a2f2f692e706f7374696d672e63632f6431586b794e64352f7a65726f746965722d312d342d362d616e792e6a7067)](https://postimg.cc/5YB2c3sz)
> 
> ```
> zerotier-cli info 
> -sh: zerotier-cli: not found
> ```
> 
> ls /dev/tun
> 
> `/dev/tun`

I'm getting exactly the same problem, trying to run the APK package as ROOT from Terminal via SSH. Is there a solution?

**Comment by ali-95** [comment]
нет еще

not yet

**Comment by crucialscott** [comment]
That sucks, really want to use this feature with my NAS! I tried updating to the latest ADM...

**Comment by ali-95** [comment]
Может он не поддерживает какие то модели ASUSTOR
Maybe it doesn't support some ASUSTOR models https://www.asustor.com/app_central/search_app?model=&keyword=zerotier

**Comment by crucialscott** [comment]
Thank you, I didn't realise there was 3 different versions! 

I've got it running, and it says its connected to my ZeroTier Network ID however it never shows ups on the ZeroTier portal..

**Comment by ali-95** [comment]
and as they started, I get an error zerotier-cli info 
-sh: zerotier-cli: not found
