### ISSUE TITLE
v1.2.12 on Synology leaking memory

### ISSUE THREAD

**Issue by fastcat** [zerotier/ZeroTierNAS#46]
The zerotier client on my Synology, running v1.2.12 (using ZT's provided binary package), is leaking memory considerably.  This is a graph from the Synology's resource monitor.  The numbers on the x axis are days of the month (Feb 2019).

![image](https://user-images.githubusercontent.com/390963/53541203-b3815f00-3ae6-11e9-97af-713bd8e3e89f.png)

The zerotier-one process is now using ~1.2GB of RAM, so that graph shows a leak of about ~50 megs a day~ _edit: I misread the y axis_ 1.1G over 10 days.  It would have brought down the NAS by itself within a month!

The NAS in question is connected to one ZT network.

Restarting the package/service cleared the leak ... for now.

Side note: the 1.2.12 package reports as version 1.2.13?

**Comment by joseph-henry** [comment]
Thanks for reporting this. I'll look into it. Are you still seeing this?

**Comment by fastcat** [comment]
It has happened again recently, yes.  Here's the memory utilization on the unit for the past month:
![image](https://user-images.githubusercontent.com/390963/56839610-4aea0080-6851-11e9-858b-0f4c2434836a.png)
The sharp drop in memory usage on the 15th was another reboot, though not related to ZT.  Curious that it hasn't started spiking again yet.  Clearly something triggers it to go from normal mode to the bad mode, but I'd be hard pressed to guess what.

**Comment by joseph-henry** [comment]
Thanks for the info. I have a suspicion that it's related to an issue that was fixed some months ago in the main edition of the service, I'll work on getting some new packages out and I'll update this thread once I do so. Sorry for the inconvenience.

**Comment by fastcat** [comment]
If updating the Synology packages, #41 is worth looking at -- the latest packages simply don't work out of the box because of that, at least not on the newer versions of the DSM

**Comment by Inklin235** [comment]
Echo what @fastcat has said. on 1.2.8 the synology was losing its Node ID on reboot and thus was booted from the network. on 1.2.12 it will not reconnect upon reboot, it says PORT_ERROR and zerotier-cli help says "zerotier-cli: missing authentication token and authtoken.secret not found (or readable) in /var/packages/zerotier/target/var" but these files are present in this directory.

**Comment by joseph-henry** [comment]
@Inklin235 which model do you have? I have some new `1.2.13` packages up now, once I know your model I will upload a package for you to test: http://download.zerotier.com/RELEASES/1.2.13/dist/synology/

**Comment by Inklin235** [comment]
@joseph-henry Thank you! We have both a DS218j and a DS416 with issues. We are using ZeroTier for a private network between these in different locations.

**Comment by fastcat** [comment]
While trying to investigate why I had issues upgrading to 1.2.13 (for #41 more than this), I came across some very suspicious logging that may point to what the error was here:

In `/var/log/packages/zerotier.log` there's a _ton_ of this kind of thing:
```
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/a9e319c8e6.peer (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/6b9bc8c066.peer (unable to open)
Error opening RTNETLINK socket: Too many open files
WARNING: unable to write to file: /var/packages/zerotier/target/var/networks.d/f912c2ea3a122510.conf (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/a9e319c8e6.peer (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/6b9bc8c066.peer (unable to open)
Error opening RTNETLINK socket: Too many open files
WARNING: unable to write to file: /var/packages/zerotier/target/var/networks.d/f912c2ea3a122510.conf (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/bff66af405.peer (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/bf1e9d72a4.peer (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/a9e319c8e6.peer (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/6b9bc8c066.peer (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/4e0dbfeaf8.peer (unable to open)
Error opening RTNETLINK socket: Too many open files
WARNING: unable to write to file: /var/packages/zerotier/target/var/networks.d/f912c2ea3a122510.conf (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/a9e319c8e6.peer (unable to open)
WARNING: unable to write to file: /var/packages/zerotier/target/var/peers.d/6b9bc8c066.peer (unable to open)
Error opening RTNETLINK socket: Too many open files
```

**Comment by RickstermUK** [comment]
@joseph-henry I see you uploaded the packages but upon trying these, neither will actually Run. If I click Run it tries to start ZeroTier but then stops.

**Comment by joseph-henry** [comment]
Hey everyone, my apologies for taking so long on this. Here's an [updated set of packages](https://download.zerotier.com/PRERELEASES/1.4.0pre/synology) to preview `1.4.0`. It addresses the following issues:

 - Memory leak (*might* be fixed)
- Losing interface on reboot: `insmod /lib/modules/tun.ko` issued upon each reboot (and start of the service). See tickets #41 and #43 
 - Identity files moved to more traditional location `/var/lib/zerotier-one`, and are now preserved across uninstalls, reinstalls, updates, etc. Prior to this version, during uninstall we were intentionally deleting your identity files just for thoroughness but this seems to be annoying to most users (rightly so). So uninstalling and updating to this version is the last time that your configuration will get wiped. See tickets #41
 - Service script now sends proper SIGKILL signal
 - Segfault on ARM#52 might* be fixed), see ticket #52

**Comment by joseph-henry** [comment]
As for the `Too many open files` issue, I suspect that is an issue related to other applications creating too many files (one such user had the same issue while running Hyperbackup). In this state I've checked the number of files in use by ZT and it was less than a dozen or so of various types.

**Comment by fastcat** [comment]
@joseph-henry Thanks for the followup.  Is there a larger list you can link to of what's new in general in ZT 1.4.0?

> So uninstalling and updating to this version is the last time that your configuration will get wiped

Can I safely assume that a process like this will prevent losing configuration across this upgrade?
1. Make a backup of the `/usr/local/zerotier/zerotier/var/` directory (other than the pid file)
2. Install the update
3. Stop ZT after the update
4. Remove the files the new version wrote to `/var/lib/zerotier/` and replace them with the backup
5. Start ZT again

**Comment by joseph-henry** [comment]
No problem. And yes the procedure you described will carry over your configuration. However note that it is `/var/lib/zerotier-one` rather than `/var/lib/zerotier`.

Additionally,

Pre-1.4.0 blog announcement: https://www.zerotier.com/zerotier-1-4-0pre/
Release notes (still in flux): https://github.com/zerotier/ZeroTierOne/blob/dev/RELEASE-NOTES.md

**Comment by davide** [comment]
@joseph-henry may I ask for a pre-release package for 88f6281 also? Thanks in advance! 🙇

**Comment by davide** [comment]
@joseph-henry this package:
https://download.zerotier.com/RELEASES/1.4.0/dist/synology/zerotier_88f6281-6.1_1.4.0-0.spk
is working perfectly! Thanks!

**Comment by fastcat** [comment]
@joseph-henry The upgrade process worked (I ended up stopping the service and copying the data files over and then installing the upgrade since that was simpler).  I've set myself a reminder to check back in here in a little while to confirm if the memory leak has gone away.  Sadly it could take over a month for it to happen before, so ... that confirmation may take a while.

**Comment by joseph-henry** [comment]
Hello again. Checking in to make sure this is no longer an issue before I close the ticket. We will be releasing another round of packages for our upcoming 1.6.0.

**Comment by fastcat** [comment]
I no longer use ZT, so I can only assume this isn't a problem any more. There weren't any signs of it between my last comment and when I stopped using ZT, so probably a safe enough assumption.
