### ISSUE TITLE
Version for Xpenology with CPU A4-5000

### ISSUE THREAD

**Issue by terryche** [zerotier/ZeroTierNAS#48]
Would like to check which version should I use for Xpenology 6.1.6 DS3615xs with A4-5000 ?

**Comment by joseph-henry** [comment]
I have no experience with Xpenology, but I would try the following packages:

http://download.zerotier.com/RELEASES/1.2.12/dist/zerotier-1.2.12r1-syn-x64-6.1.spk
http://download.zerotier.com/RELEASES/1.2.12/dist/zerotier-1.2.12r1-syn-broadwell-6.1.spk
