### ISSUE TITLE
PORT_ERROR DS918+

### ISSUE THREAD

**Issue by eepohboy** [zerotier/ZeroTierNAS#53]
I have noticed recently that ZT does not connect properly after rebooting my NAS. All preconfigured settings: network, IP, etc are there when I listnetworks, but under status it says PORT_ERROR.

Leaving and rejoining the network does not fix the problem.

The only thing that seems to work is uninstalling and reinstalling the package, and adding the new member ID to my network.

Package version I'm using is 1.2.12r1

### I have tried the following:

- [Y ] Disabling QuickConnect
- [NA ] Disabling OpenVPN
- [NA ] Restoring web port to default (5000/5001)
- [Y] Restarting NAS
- [Y] Reinstall ZT
- [ ] Checked for presence of `dev/net/tun`
- [ ] Verified that ZT is or is not running with `ps aux | grep zerotier`
- [ ] confirmed that config files exist in `/var/packages/zerotier/target/var`
- [Y] Issued `zerotier-cli` commands as root

### I am aware of the following

- [Y ] The GUI is deprecated and may not work on my particular NAS
- [Y ] The CLI is the recommended interface for controlling ZT

### Other important information

- Model:DS918+
- Current DSM version: 6.2.2-24922 Update 2
- DSM version when issue was first observed:
6.2.2-24922 Update 1

**Comment by Dbone29** [comment]
I have the same problem. I can fix it by restarting ZeroTier within the package manager after a reboot.

**Comment by eepohboy** [comment]
So the one thing on the checklist I did not do was check whether /dev/net/tun was present. After a recent power outage, and after the NAS rebooted, I got the same error under status when running listnetworks: PORT_ERROR.

This time I checked for /dev/net/tun, and found that it was missing. After doing a bit more Googling, I found [this guide](https://ruimarinho.github.io/post/fix-tun-tap-not-available-on-a-synology-nas/) which runs through a few troubleshooting steps and how to make the fix persistent. After running the insmod command, PORT_ERROR goes away and everything is back to normal. So it looks like /dev/net/tun goes away after my NAS reboots.

However, I feel that this shouldn't be happening by default. It seems to be a known issue, since it's on the checklist of things to try, but my initial searching about the error did not produce any obvious results that this was a problem. If it is a "feature" and not a bug, at least document it, or point users to [a fix](https://ruimarinho.github.io/post/fix-tun-tap-not-available-on-a-synology-nas/) so that if they come across this problem, they know what to do. 

My 2c.

**Comment by cinghialino** [comment]
Same problem here. It affects both of my Synology NASs: DS1817+ and DS218j. 
They are both running DSM v6.2.2

**Comment by alatteri** [comment]
Joseph made a fix to the Synology packages ~2 months ago.  Maybe they never made it into the release though.  He provided me special packages directly.

**Comment by joseph-henry** [comment]
Hey everyone, my apologies for taking so long on this. Here's an [updated set of packages](https://download.zerotier.com/PRERELEASES/1.4.0pre/synology) to preview `1.4.0`. It addresses the following issues:

 - Losing interface on reboot: `insmod /lib/modules/tun.ko` issued upon each reboot (and start of the service). See tickets #41 and #43 
 - Identity files moved to more traditional location `/var/lib/zerotier-one`, and are now preserved across uninstalls, reinstalls, updates, etc. Prior to this version, during uninstall we were intentionally deleting your identity files just for thoroughness but this seems to be annoying to most users (rightly so). So uninstalling and updating to this version is the last time that your configuration will get wiped. See tickets #41
 - Service script now sends proper SIGKILL signal
 - Segfault on ARM (*might* be fixed), see ticket #52
 - Memory leak (*might* be fixed), see ticket #46

To view logs for this package, see: `/var/log/packages/zerotier.log`

**Comment by cinghialino** [comment]
the armada 38x version is not starting.

**Comment by joseph-henry** [comment]
Does it say anything if you ssh in and try to run: `sudo /volume1/@appstore/zerotier/bin/zerotier-one`

Assuming your installation is on `volume1` that is.

**Comment by donlassini** [comment]
I have the same issue on my ds218j.
I tried installing the update and did the ssh instruction you asked for:

admin@ds218j:/volume1/@appstore/zerotier/bin$ sudo ./zerotier-one
pure virtual method called
terminate called without an active exception
Aborted
admin@ds218j:/volume1/@appstore/zerotier/bin$

**Comment by joseph-henry** [comment]
Closing this ticket due to age. We intend to fix this issue and support the DS918+ with our upcoming 1.6.0 packages. If this issue persists with the new packages please re-open another ticket.

The DS218j may not receive support in the 1.6.0 packages but I will try my best. After these new packages are released I would recommend opening a new (separate) ticket if this issue exists.
