### ISSUE TITLE
Can't install zerotier on my synology DS215j with DSM 6.0.3

### ISSUE THREAD

**Issue by gb0519** [zerotier/ZeroTierNAS#54]
My synology device: DS215j with DSM 6.0.3-8754 Update 8
When I am trying to install zerotier-1.2.12r1-syn-armada375-6.0.2.spk manually.

This error appears and then the installation failed:
"This package does not contain digital signature"

**Comment by joseph-henry** [comment]
You need to adjust the trust level for 3rd party apps. It's somewhere in the settings near the manual install section.
