### ISSUE TITLE
Issue installing package on Synology DS119j with 6.2.2-24922 Update 2

### ISSUE THREAD

**Issue by tomSCJE** [zerotier/ZeroTierNAS#55]
Hey everyone, I am hoping someone might be able to help. I am trying to install the ZeroTier package onto a Synology NAS and feel like I'm missing something very simple.

It is a Synology DS119j, MARVELL Armada 3720 CPU, DSM version 6.2.2-24922 Update 2. I download the SPK from https://download.zerotier.com/dist/synology/, tried all the armada versions along with the x64 versions. From the web interface I go to the package center, upload a package for manual installation, select the SPK I downloaded but regardless of which version of the SPK it tells me "This package is not supported on the platform of Diskstation or is incompatible with the current DSM version."

I've not done this type of setup before but from what I've seen it should work with that particular Synology NAS. Is there more to it that just downloading the SPK and trying to upload it? I can't really find anything in the forums or support posts about the installation.

**Comment by joseph-henry** [comment]
We have a set of 1.4.0 pre-release builds. The only package that would work with your model is: https://download.zerotier.com/PRERELEASES/1.4.0pre/synology/zerotier_armada37xx-6.2_1.4.0.spk

A new set of 1.4.0 regular release packages will come soon but only after I confirm that these work so please update this ticket after you've tried the package on your system. Thank you.

**Comment by Dev-DCH** [comment]
Hello there!

You know, I bought the Synology DS119j, MARVELL Armada 3720 CPU, DSM version 6.2.2-24922 five days ago and I tried each of the ZeroTier packages released on the official web... none of them work.
But then I found this solution in here so I installed the 1.4.0 package and works perfectly since I installed 3 days ago.

Thank you so much buddy!!! You can remove the BETA label on it 👍

**Comment by neekin** [comment]
it's work,thnaks

**Comment by carballada** [comment]
Also installed/running on 
![image](https://user-images.githubusercontent.com/6533660/82675344-fd52e980-9c44-11ea-891e-ef55d2b17ff8.png)
with no troubles!!! thank you so much!!!

**Comment by joseph-henry** [comment]
Glad to hear this worked!
