### ISSUE TITLE
Hello I installed zerotier.spk on a synology DS3617xs - DSM 6.2.2 installation successfully, I inserted the id, and when I clicked join, nothing happens I downloaded it from http://download.zerotier.com/RELEASES/1.2.13/dist/synology/ I installed the version zerotier_x64-6.1_1.2.13-1.spk Can you help me please

### ISSUE THREAD

**Issue by nandrianina25** [zerotier/ZeroTierNAS#60]
### I have tried the following:

- [ ] Disabling QuickConnect
- [ ] Disabling OpenVPN
- [ ] Restoring web port to default (5000/5001)
- [x] Restarting NAS
- [x] Reinstall ZT
- [ ] Checked for presence of `dev/net/tun`
- [ ] Verified that ZT is or is not running with `ps aux | grep zerotier`
- [ ] confirmed that config files exist in `/var/packages/zerotier/target/var`
- [ ] Issued `zerotier-cli` commands as root

### I am aware of the following

- [ ] The GUI is deprecated and may not work on my particular NAS
- [ ] The CLI is the recommended interface for controlling ZT

### Other important information

- Model:
- Current DSM version:
- DSM version when issue was first observed:

**Comment by joseph-henry** [comment]
Have you tried using the CLI? What happens?

**Comment by nandrianina25** [comment]
how to use the CLI please? I have already reinstalled zerotier, restarted the NAS

**Comment by nandrianina25** [comment]
when I do zerotier-cli, I have this
/$ zerotier-cli info
zerotier-cli: missing port and zerotier-one.port not found in /var/packages/zerotier/target/var

**Comment by nandrianina25** [comment]
hi! can you help me please

**Comment by clintmod** [comment]
@nandrianina25 and after I installed the app via ssh I had to go in to the web UI and click "Run". There is a UI in the web interface you can use to join a network.
