### ISSUE TITLE
DS215J Build

### ISSUE THREAD

**Issue by go626201** [zerotier/ZeroTierNAS#62]
Is DS215J not supported anymore?
I cant find any build for the nas.

**Comment by wei** [comment]
I got version 1.2.8, it seems to work ok. https://download.zerotier.com/RELEASES/1.2.8/dist/synology/

**Comment by joseph-henry** [comment]
Correct. 1.2.8 is the latest version that supports the order Marvell chipsets. This may change in the upcoming 1.6.0 packages. Closing this ticket for now.
