### ISSUE TITLE
Newer version for QNAP?

### ISSUE THREAD

**Issue by narze** [zerotier/ZeroTierNAS#63]
I see only 1.2.12 builds for QNAP, can I build 1.4 myself?

**Comment by michaelsmoody** [comment]
By any chance, before I start down the road of trying to do so, were you able to build a newer version for your QNAP?

**Comment by narze** [comment]
I did not try to build it since I have not found the build script and using the old version is ok for me

Noom

**Comment by joseph-henry** [comment]
Noted. I will be making a new set of 1.6.0 packages for QNAP soon.
