### ISSUE TITLE
DS218+ Join button does nothing

### ISSUE THREAD

**Issue by maxwell-01** [zerotier/ZeroTierNAS#67]
I followed the link to download the correct (apollolake) package and installed.

Pressing the join button after pasting in the ID does nothing.

Have also tried installing both x64 packages which do the same.

**Comment by maxwell-01** [comment]
When trying to use the command line interface, the info command produces the following:

401 info {}

**Comment by maxwell-01** [comment]
Never heard back from support and tried many solutions found online. Finally decided to factory reset the NAS which solved the problem.

**Comment by joseph-henry** [comment]
Hello @maxwell-01 Just FYI, the GUI has been deprecated in favor of the CLI. If you have any more issues feel free to re-open this ticket.
