### ISSUE TITLE
Cant install Package on Synology DS215j

### ISSUE THREAD

**Issue by Keks666** [zerotier/ZeroTierNAS#69]
- Model:  Synology DS215j
- Current DSM version: DSM 6.2.2-24922 Update 4
- DSM version when issue was first observed: DSM 6.2.2-24922 Update 4

I can't install any of the .spk files. I always get an error, that it's not suitable for the DiskStation platform or compatible with the DSM version. :(
Need help!
![error](https://user-images.githubusercontent.com/60568493/73606581-0d6a8e80-45ac-11ea-97bc-e343c2000a9c.jpg)

**Comment by rklomp** [comment]
Unfortunately only the old 1.2.x versions are available for this CPU architecture:
https://download.zerotier.com/RELEASES/1.2.8/dist/synology/zerotier-1.2.8r0-syn-armada375-6.1.spk

@joseph-henry , how could we get the 1.4.x versions for armada375 and armadaxp?

**Comment by joseph-henry** [comment]
@rklomp That is correct. I'm hoping to support the older chipsets again with the upcoming 1.6.0 packages.
