### ISSUE TITLE
Synology DS916+ no external access thuogh ONLINE and Connected

### ISSUE THREAD

**Issue by jchwilson837** [zerotier/ZeroTierNAS#78]
### I have tried the following:

- [x] Disabling QuickConnect
- [x] Disabling OpenVPN
- [x] Restoring web port to default (5000/5001)
- [x] Restarting NAS
- [x] Reinstall ZT
- [x] Checked for presence of `dev/net/tun`
- [x] Verified that ZT is or is not running with `ps aux | grep zerotier`
- [x] confirmed that config files exist in `/var/packages/zerotier/target/var`
- [x] Issued `zerotier-cli` commands as root

### I am aware of the following

- [x] The GUI is deprecated and may not work on my particular NAS
- [x] The CLI is the recommended interface for controlling ZT

### Other important information

- Model:
- Current DSM version:
- DSM version when issue was first observed:

**Comment by joseph-henry** [comment]
Hello. Are you still experiencing this issue? I don't see your DSM version listed in the report. If you could provide that it may help.
