### ISSUE TITLE
DS918+ interface speed only (reporting) 10Mb/s?

### ISSUE THREAD

**Issue by 81pla** [zerotier/ZeroTierNAS#79]
- Model: DS918+
- Current DSM version: 6.2.3
- Installed Zerotier version :zerotier_x64-6.1_1.4.0-0.spk

all function work well , but zerotier interface speed only 10Mb/s. physical interface has 1000Mb/s.

![image](https://user-images.githubusercontent.com/17949410/88499961-0ae86f00-cffa-11ea-83a2-c96d53063772.png)

**Comment by joseph-henry** [comment]
Hello.

As far as I know that is merely a limitation of how a `tun` in the Linux kernel will report its speed. No matter the performance it will always report `10 Mb/s` but you should get much more out of it.

Have you tested the performance?
