### ISSUE TITLE
DS215J could not work well

### ISSUE THREAD

**Issue by IxsCN** [zerotier/ZeroTierNAS#8]
```
root@NAS:~# cat /proc/cpuinfo 
Processor       : ARMv7 Processor rev 1 (v7l)
processor       : 0
BogoMIPS        : 1594.16

processor       : 1
BogoMIPS        : 1594.16

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

Hardware        : Marvell Armada-375 Board
Revision        : 0000
Serial          : 0000000000000000
root@NAS:~# zerotier-cli join xxxxxxxxxxxx
zerotier-cli: missing authentication token and authtoken.secret not found (or readable) in /var/lib/zerotier-one

```
it seem  zerotier-idtool not work well

**Comment by joseph-henry** [comment]
Your device uses the Armada 375 88F6720 Processor. Try this: https://download.zerotier.com/dist/zerotier-1.2.4-syn-armada375-6.1.spk

Since I don't have one of these devices in-house it would be fantastic if you could let me know if this fixes your problems (or creates others).

Thanks

**Comment by IxsCN** [comment]
![image](https://user-images.githubusercontent.com/5812326/33642486-313d4860-da75-11e7-90ae-50e6115e44f0.png)

UI not work , But command works well .

```
root@Ixs:~# zerotier-cli join xxxxxxxxxxxxxxxx
200 join OK
root@Ixs:~# zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks xxxxxxxxxxxxxxxx NET xx:xx:xx:xx:xx:xx OK PRIVATE eth50 -
```

thank you

**Comment by joseph-henry** [comment]
Glad that's working at least. 

Can you right click in your browser when the GUI is open and view the console? I'm curious what errors we might see. Are you trying to access this via http or https?

**Comment by IxsCN** [comment]
Chrome‘s console?

**Comment by joseph-henry** [comment]
@IxsCN If you're still experiencing GUI problems can you provide me with the following information:

 - Browser (version if possible)
 - Specific errors from your Browser's console
 - Extensions installed (try disabling them to see if that helps)
 - Any information about how you're remotely connecting to your NAS
 - Whether you have a firewall enabled
 - Any non-default settings on the NAS

Thanks for your patience.

**Comment by IxsCN** [comment]
so sorry!
The problem had been solved,
Zerotier not start when NAS reboot, 
so just start the Zerotier, and it works very well.
thx
