### ISSUE TITLE
[Feature Request] work on the synology dsm 7.0

### ISSUE THREAD

**Issue by U3DC** [zerotier/ZeroTierNAS#83]
update to the synology dsm 7.0 ZeroTier is no long work.

**Comment by joseph-henry** [comment]
Hello @U3DC, 

I've transferred your request to https://github.com/zerotier/ZeroTierNAS and will update this ticket once I've added support.

**Comment by elxroman** [comment]
DSM 7.0 Beta download link -> https://prerelease.synology.com/en-global/download/dsm70_beta

**Comment by U3DC** [comment]
use docker version is okay~

**Comment by DoctorZIP** [comment]
> use docker version is okay~

It's not okay. Did you try to access Synology File Manager via docker container?

**Comment by drdoug007** [comment]
Will the Docker version survive a DSM update?
If not this is a crap solution for people who remotely access their Synology via ZeroTier
