### ISSUE TITLE
Synology DS213J

### ISSUE THREAD

**Issue by TYLERCHEN999** [zerotier/ZeroTierNAS#85]
Hey, I am trying to install the ZeroTier package onto my Synology NAS and  I just can't find the correct ZeroTier version on the download page(https://download.zerotier.com/dist/synology/).

It is a Synology D213j, MARVELL Armada 370 CPU, DSM version 6.2.3-25426 Update 2. 

I am hoping someone might be able to help.

Thanks

**Comment by Nionor** [comment]
You probably found it by now but you need to use an older version.
I'm using https://download.zerotier.com/RELEASES/1.2.12/dist/synology/ on a DS215j and it works fine.

**Comment by joseph-henry** [comment]
Here are the latest [1.8.6 packages for DSM 6.2.4](http://download.zerotier.com/RELEASES/1.8.6/dist/synology/). Including a build for the Armada 370. Let me know if you have any issues.

We'll continue to periodically make releases for DSM 6 until Synology officially EOLs it in 2023.
